<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\LocationsController;
use FortisAPILib\Exceptions;

class LocationsControllerTest extends BaseTestController
{
    /**
     * @var LocationsController LocationsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getLocationsController();
    }

    public function testTestListAllLocations()
    {
        // Parameters for the API call
        $page = null;
        $sort = null;
        $filter = null;
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllLocations($page, $sort, $filter, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationsCollection","list":[{"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992,"account_number":"5454545454545454","' .
                'address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US","stre' .
                'et":"43155 Main Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"b' .
                'randing_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_defaul' .
                't":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e0' .
                '92242dda","developer_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"e' .
                'mail@domain.com","fax":"3339998822","location_api_id":"location-111111","locati' .
                'on_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"' .
                'custom 2","location_c3":"custom data 3","name":"Sample Company Headquarters","o' .
                'ffice_phone":"2481234567","office_ext_phone":"1021021209","recurring_notificati' .
                'on_days_default":0,"tz":"America/New_York"}],"links":{"type":"Links","first":"/' .
                'v1/endpoint?page[size]=10&page[number]=1","previous":"/v1/endpoint?page[size]=1' .
                '0&page[number]=5","last":"/v1/endpoint?page[size]=10&page[number]=42"},"paginat' .
                'ion":{"type":"Pagination","total_count":423,"page_count":42,"page_number":6,"pa' .
                'ge_size":10},"sort":{"type":"Sorting","fields":[{"field":"last_name","order":"a' .
                'sc"}]}}'
            )))
            ->assert();
    }

    public function testTestLocationsDetail()
    {
        // Parameters for the API call
        $page = null;
        $sort = null;
        $filter = null;
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->locationsDetail($page, $sort, $filter, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationInfosCollection","list":[{"id":"11e95f8ec39de8fbdb0a4f1a","cr' .
                'eated_ts":1422040992,"modified_ts":1422040992,"account_number":"545454545454545' .
                '4","address":{"city":"Novi","state":"MI","postal_code":"48375","country":"US","' .
                'street":"43155 Main Street STE 2310-C","street2":"43155 Main Street STE 2310-C"' .
                '},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_de' .
                'fault":true,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5' .
                'f1e092242dda","developer_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to' .
                '":"email@domain.com","fax":"3339998822","location_api_id":"location-111111","lo' .
                'cation_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c' .
                '2":"custom 2","location_c3":"custom data 3","name":"Sample Company Headquarters' .
                '","office_phone":"2481234567","office_ext_phone":"1021021209","recurring_notifi' .
                'cation_days_default":0,"tz":"America/New_York","branding_domain_url":"subdomain' .
                '.sandbox.domain.com","branding_domain":{},"product_transactions":[null],"produc' .
                't_file":{},"product_accountvault":{},"product_recurring":{},"tags":[null],"term' .
                'inals":[null]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&pag' .
                'e[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","last":"/v1' .
                '/endpoint?page[size]=10&page[number]=42"},"pagination":{"type":"Pagination","to' .
                'tal_count":423,"page_count":42,"page_number":6,"page_size":10},"sort":{"type":"' .
                'Sorting","fields":[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testTestViewSingleLocationRecord()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleLocationRecord($locationId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Location","data":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992,"account_number":"5454545454545454","address":{"c' .
                'ity":"Novi","state":"MI","postal_code":"48375","country":"US","street":"43155 M' .
                'ain Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"branding_doma' .
                'in_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"def' .
                'ault_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","d' .
                'eveloper_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.' .
                'com","fax":"3339998822","location_api_id":"location-111111","location_api_key":' .
                '"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","l' .
                'ocation_c3":"custom data 3","name":"Sample Company Headquarters","office_phone"' .
                ':"2481234567","office_ext_phone":"1021021209","recurring_notification_days_defa' .
                'ult":0,"tz":"America/New_York"}}'
            )))
            ->assert();
    }

    public function testTestLocationDetail()
    {
        // Parameters for the API call
        $locationId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->locationDetail($locationId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"LocationInfo","data":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14' .
                '22040992,"modified_ts":1422040992,"account_number":"5454545454545454","address"' .
                ':{"city":"Novi","state":"MI","postal_code":"48375","country":"US","street":"431' .
                '55 Main Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"branding_' .
                'domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,' .
                '"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda' .
                '","developer_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@dom' .
                'ain.com","fax":"3339998822","location_api_id":"location-111111","location_api_k' .
                'ey":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2' .
                '","location_c3":"custom data 3","name":"Sample Company Headquarters","office_ph' .
                'one":"2481234567","office_ext_phone":"1021021209","recurring_notification_days_' .
                'default":0,"tz":"America/New_York","branding_domain_url":"subdomain.sandbox.dom' .
                'ain.com","branding_domain":{},"product_transactions":[null],"product_file":{},"' .
                'product_accountvault":{},"product_recurring":{},"tags":[null],"terminals":[null' .
                ']}}'
            )))
            ->assert();
    }
}
