<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\RecurringController;
use FortisAPILib\Exceptions;

class RecurringControllerTest extends BaseTestController
{
    /**
     * @var RecurringController RecurringController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getRecurringController();
    }

    public function testTestListAllRecurringRecord()
    {
        // Parameters for the API call
        $page = null;
        $sort = null;
        $filter = null;
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllRecurringRecord($page, $sort, $filter, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"RecurringsCollection","list":[{"account_vault_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","active":true,"description":"Description","end_date":"2021-12-01","inst' .
                'allment_total_count":20,"interval":1,"interval_type":"d","location_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","product_transac' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","status":"activ' .
                'e","transaction_amount":3,"terms_agree":true,"terms_agree_ip":"192.168.0.10","r' .
                'ecurring_c1":"recurring custom data 1","recurring_c2":"recurring custom data 2"' .
                ',"recurring_c3":"recurring custom data 3","send_to_proc_as_recur":true,"id":"11' .
                'e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992,"m' .
                'odified_ts":1422040992,"recurring_type_id":"i","log_emails":[{"subject":"Paymen' .
                't Receipt - 12skiestech","body":"This email is being sent from a server.","sour' .
                'ce_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"' .
                '\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc' .
                '530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbd' .
                'b0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_mod' .
                'el_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.c' .
                'om>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"loca' .
                'tion_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api' .
                '_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822","b' .
                'alance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375' .
                '","country":"US","street":"43155 Main Street STE 2310-C"},"company_name":"Forti' .
                's Payment Systems, LLC","header_message":"This is a sample message for you","da' .
                'te_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","o' .
                'ffice_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"updat' .
                'e_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"somethi' .
                'ng","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e' .
                '95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active' .
                '":true},"account_vault":{"account_holder_name":"John Smith","account_number":"5' .
                '45454545454545","account_vault_api_id":"accountvaultabcd","accountvault_c1":"ac' .
                'countvault custom 1","accountvault_c2":"accountvault custom 2","accountvault_c3' .
                '":"accountvault custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi"' .
                ',"state":"Michigan","postal_code":"48375","street":"43155 Main Street STE 2310-' .
                'C","phone":"3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":' .
                '"123456","identity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":' .
                '"8527","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_ac' .
                'count_vault_api_id":"previousaccountvault123456","previous_account_vault_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summa' .
                'ry_status_id":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track' .
                '_data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"firs' .
                't_six":"700953","has_recurring":false,"last_four":"3657","modified_ts":14220409' .
                '92,"payment_method":"cc","ticket":null,"track_data":null},"created_user":{"acco' .
                'unt_number":"5454545454545454","address":"43155 Main Street STE 2310-C","brandi' .
                'ng_domain_url":"{branding_domain_url}","cell_phone":"3339998822","city":"Novi",' .
                '"company_name":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","date_of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","emai' .
                'l":"email@domain.com","email_trx_receipt":true,"home_phone":"3339998822","first' .
                '_name":"John","last_name":"Smith","locale":"en-US","office_phone":"3339998822",' .
                '"office_ext_phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requir' .
                'es_new_password":null,"state":"Michigan","terms_condition_code":"20220308","tz"' .
                ':"America/New_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_' .
                'export_type":"csv","process_method":"virtual_terminal","default_terminal":"11e9' .
                '5f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f' .
                '923w2","user_hash_key":null,"user_type_code":100,"password":null,"zip":"48375",' .
                '"location_id":"11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8f' .
                'bdb0a4f1a","status":true,"login_attempts":0,"last_login_ts":1422040992,"created' .
                '_ts":1422040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_' .
                'date_time":"2019-03-11T10:38:26-0700"},"signature":{"signature":"iVBORw0KGgoAAA' .
                'ANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRi' .
                'UajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsI' .
                'znFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOv' .
                'YNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ' .
                '7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VX' .
                'hRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdn' .
                'PKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5' .
                'zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs' .
                '2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVU' .
                'FifDOo7THxmPiY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5' .
                'PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoP' .
                'X4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWER' .
                'xgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","r' .
                'esource_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created' .
                '_ts":1422040992,"modified_ts":1422040992},"payment_schedule":["2021-12-01"],"lo' .
                'cation":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":' .
                '1422040992,"account_number":"5454545454545454","address":{"city":"Novi","state"' .
                ':"MI","postal_code":"48375","country":"US","street":"43155 Main Street STE 2310' .
                '-C","street2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7' .
                'd515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998' .
                '822","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BB' .
                'CAADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"custom' .
                ' data 3","name":"Sample Company Headquarters","office_phone":"2481234567","offi' .
                'ce_ext_phone":"1021021209","recurring_notification_days_default":0,"tz":"Americ' .
                'a/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CAD' .
                'F4AE34BBCAADF4"},"product_transaction":{"processor_version":"1_0_0","title":"My' .
                ' terminal","payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharg' .
                'e_config":2,"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","su' .
                'rcharge":{},"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,' .
                '"vt_enable_tip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_' .
                'refund":true,"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"' .
                'vt_enable":true,"receipt_show_contact_name":true,"display_avs":true,"card_type_' .
                'visa":true,"card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"car' .
                'd_type_diners":true,"card_type_jcb":true,"invoice_location":true,"allow_partial' .
                '_authorization":true,"allow_recurring_partial_authorization":true,"auto_decline' .
                '_cvv":true,"auto_decline_street":true,"auto_decline_zip":true,"split_payments_a' .
                'llow":true,"vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_o' .
                'verride_sales_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":tru' .
                'e,"vt_require_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_che' .
                'ck_per_batch":null,"quick_invoice_allow":false,"level3_allow":false,"payfac_ena' .
                'ble":false,"sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_al' .
                'low":false,"surcharge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":null,"cau' .
                '_subscribe_type_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2",' .
                '"product_billing_group_id":"nofees","account_number":"12345678","run_avs_on_acc' .
                'ountvault_create":false,"accountvault_expire_notification_email_enable":false,"' .
                'debit_allow_void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"v' .
                't_show_currency":true,"receipt_show_currency":false,"allow_blind_refund":false,' .
                '"vt_show_company_name":false,"receipt_show_company_name":false,"bank_funded_onl' .
                'y":false,"id":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,' .
                '"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified' .
                '_user_id":"11e95f8ec39de8fbdb0a4f1a"},"next_run_date_min":"2021-12-01","next_ru' .
                'n_date_max":"2021-12-01","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","tit' .
                'le":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992}],"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","ti' .
                'tle":"My terminal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"mod' .
                'ified_ts":1422040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_' .
                'ts":1422040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec8' .
                '29598f0d4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[' .
                '{"id":"11e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","fie' .
                'ld":"next_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a' .
                '4f1a","username":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}' .
                '],"forecast":{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","cr' .
                'eated_ts":1422040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8f' .
                'bdb0a4f1a"}]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]=10&page' .
                '[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","last":"/v1/' .
                'endpoint?page[size]=10&page[number]=42"},"pagination":{"type":"Pagination","tot' .
                'al_count":423,"page_count":42,"page_number":6,"page_size":10},"sort":{"type":"S' .
                'orting","fields":[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testTestDeleteRecurringRecord()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteRecurringRecord($recurringId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","act' .
                'ive":true,"description":"Description","end_date":"2021-12-01","installment_tota' .
                'l_count":20,"interval":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","notification_days":2,"payment_method":"cc","product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_ap' .
                'i_id":"recurring1234abcd","start_date":"2021-12-01","status":"active","transact' .
                'ion_amount":3,"terms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1"' .
                ':"recurring custom data 1","recurring_c2":"recurring custom data 2","recurring_' .
                'c3":"recurring custom data 3","send_to_proc_as_recur":true,"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992,"modified_ts":' .
                '1422040992,"recurring_type_id":"i","log_emails":[{"subject":"Payment Receipt - ' .
                '12skiestech","body":"This email is being sent from a server.","source_address":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skieste' .
                'ch A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4' .
                '-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","re' .
                'ason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","' .
                'first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.' .
                '36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country":' .
                '"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment Sy' .
                'stems, LLC","header_message":"This is a sample message for you","date_of_birth"' .
                ':"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone"' .
                ':"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists"' .
                ':1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de8f' .
                'bdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"acc' .
                'ount_vault":{"account_holder_name":"John Smith","account_number":"5454545454545' .
                '45","account_vault_api_id":"accountvaultabcd","accountvault_c1":"accountvault c' .
                'ustom 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountva' .
                'ult custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","street":"43155 Main Street STE 2310-C","phone":"' .
                '3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","id' .
                'entity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_' .
                'year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_' .
                'api_id":"previousaccountvault123456","previous_account_vault_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terms_agree"' .
                ':true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summary_status_id' .
                '":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,' .
                '"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"first_six":"7009' .
                '53","has_recurring":false,"last_four":"3657","modified_ts":1422040992,"payment_' .
                'method":"cc","ticket":null,"track_data":null},"created_user":{"account_number":' .
                '"5454545454545454","address":"43155 Main Street STE 2310-C","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","city":"Novi","company_nam' .
                'e":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_' .
                'of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@do' .
                'main.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John' .
                '","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_' .
                'phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_passw' .
                'ord":null,"state":"Michigan","terms_condition_code":"20220308","tz":"America/Ne' .
                'w_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type"' .
                ':"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fb' .
                'db0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user' .
                '_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040' .
                '992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","term' .
                's_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"' .
                '2019-03-11T10:38:26-0700"},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAAN' .
                'wAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJR' .
                'CKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6' .
                'GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURR' .
                'NMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY8' .
                '3zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUr' .
                'mr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT' .
                '647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6J' .
                'aLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2' .
                'yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmP' .
                'iY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU' .
                '53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/' .
                'Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYB' .
                'HBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040' .
                '992,"modified_ts":1422040992},"payment_schedule":["2021-12-01"],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2' .
                '":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09324' .
                '2bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","locati' .
                'on_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","loc' .
                'ation_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","na' .
                'me":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone' .
                '":"1021021209","recurring_notification_days_default":0,"tz":"America/New_York",' .
                '"parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAAD' .
                'F4"},"product_transaction":{"processor_version":"1_0_0","title":"My terminal","' .
                'payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,' .
                '"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},' .
                '"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_t' .
                'ip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true' .
                ',"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":t' .
                'rue,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,"' .
                'card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_diner' .
                's":true,"card_type_jcb":true,"invoice_location":true,"allow_partial_authorizati' .
                'on":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,"' .
                'auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,"' .
                'vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sale' .
                's_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_requir' .
                'e_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch' .
                '":null,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"' .
                'sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"' .
                'surcharge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":null,"cau_subscribe_t' .
                'ype_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_bil' .
                'ling_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_cr' .
                'eate":false,"accountvault_expire_notification_email_enable":false,"debit_allow_' .
                'void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_curre' .
                'ncy":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_com' .
                'pany_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts' .
                '":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"},"next_run_date_min":"2021-12-01","next_run_date_max":' .
                '"2021-12-01","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My term' .
                'inal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992}],"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My ter' .
                'minal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14' .
                '22040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008' .
                'be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_ru' .
                'n_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","usern' .
                'ame":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],"forecast"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","created_ts":14' .
                '22040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}]' .
                '}}'
            )))
            ->assert();
    }

    public function testTestViewSingleRecurringRecord()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleRecurringRecord($recurringId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","act' .
                'ive":true,"description":"Description","end_date":"2021-12-01","installment_tota' .
                'l_count":20,"interval":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","notification_days":2,"payment_method":"cc","product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_ap' .
                'i_id":"recurring1234abcd","start_date":"2021-12-01","status":"active","transact' .
                'ion_amount":3,"terms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1"' .
                ':"recurring custom data 1","recurring_c2":"recurring custom data 2","recurring_' .
                'c3":"recurring custom data 3","send_to_proc_as_recur":true,"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992,"modified_ts":' .
                '1422040992,"recurring_type_id":"i","log_emails":[{"subject":"Payment Receipt - ' .
                '12skiestech","body":"This email is being sent from a server.","source_address":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skieste' .
                'ch A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4' .
                '-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","re' .
                'ason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","' .
                'first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.' .
                '36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country":' .
                '"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment Sy' .
                'stems, LLC","header_message":"This is a sample message for you","date_of_birth"' .
                ':"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone"' .
                ':"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists"' .
                ':1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de8f' .
                'bdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"acc' .
                'ount_vault":{"account_holder_name":"John Smith","account_number":"5454545454545' .
                '45","account_vault_api_id":"accountvaultabcd","accountvault_c1":"accountvault c' .
                'ustom 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountva' .
                'ult custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","street":"43155 Main Street STE 2310-C","phone":"' .
                '3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","id' .
                'entity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_' .
                'year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_' .
                'api_id":"previousaccountvault123456","previous_account_vault_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terms_agree"' .
                ':true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summary_status_id' .
                '":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,' .
                '"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"first_six":"7009' .
                '53","has_recurring":false,"last_four":"3657","modified_ts":1422040992,"payment_' .
                'method":"cc","ticket":null,"track_data":null},"created_user":{"account_number":' .
                '"5454545454545454","address":"43155 Main Street STE 2310-C","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","city":"Novi","company_nam' .
                'e":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_' .
                'of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@do' .
                'main.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John' .
                '","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_' .
                'phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_passw' .
                'ord":null,"state":"Michigan","terms_condition_code":"20220308","tz":"America/Ne' .
                'w_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type"' .
                ':"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fb' .
                'db0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user' .
                '_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040' .
                '992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","term' .
                's_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"' .
                '2019-03-11T10:38:26-0700"},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAAN' .
                'wAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJR' .
                'CKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6' .
                'GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURR' .
                'NMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY8' .
                '3zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUr' .
                'mr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT' .
                '647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6J' .
                'aLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2' .
                'yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmP' .
                'iY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU' .
                '53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/' .
                'Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYB' .
                'HBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040' .
                '992,"modified_ts":1422040992},"payment_schedule":["2021-12-01"],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2' .
                '":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09324' .
                '2bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","locati' .
                'on_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","loc' .
                'ation_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","na' .
                'me":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone' .
                '":"1021021209","recurring_notification_days_default":0,"tz":"America/New_York",' .
                '"parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAAD' .
                'F4"},"product_transaction":{"processor_version":"1_0_0","title":"My terminal","' .
                'payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,' .
                '"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},' .
                '"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_t' .
                'ip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true' .
                ',"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":t' .
                'rue,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,"' .
                'card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_diner' .
                's":true,"card_type_jcb":true,"invoice_location":true,"allow_partial_authorizati' .
                'on":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,"' .
                'auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,"' .
                'vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sale' .
                's_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_requir' .
                'e_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch' .
                '":null,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"' .
                'sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"' .
                'surcharge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":null,"cau_subscribe_t' .
                'ype_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_bil' .
                'ling_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_cr' .
                'eate":false,"accountvault_expire_notification_email_enable":false,"debit_allow_' .
                'void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_curre' .
                'ncy":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_com' .
                'pany_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts' .
                '":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"},"next_run_date_min":"2021-12-01","next_run_date_max":' .
                '"2021-12-01","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My term' .
                'inal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992}],"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My ter' .
                'minal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14' .
                '22040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008' .
                'be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_ru' .
                'n_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","usern' .
                'ame":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],"forecast"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","created_ts":14' .
                '22040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}]' .
                '}}'
            )))
            ->assert();
    }

    public function testTestActivateRecurringPayment()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->activateRecurringPayment($recurringId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","act' .
                'ive":true,"description":"Description","end_date":"2021-12-01","installment_tota' .
                'l_count":20,"interval":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","notification_days":2,"payment_method":"cc","product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_ap' .
                'i_id":"recurring1234abcd","start_date":"2021-12-01","status":"active","transact' .
                'ion_amount":3,"terms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1"' .
                ':"recurring custom data 1","recurring_c2":"recurring custom data 2","recurring_' .
                'c3":"recurring custom data 3","send_to_proc_as_recur":true,"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992,"modified_ts":' .
                '1422040992,"recurring_type_id":"i","log_emails":[{"subject":"Payment Receipt - ' .
                '12skiestech","body":"This email is being sent from a server.","source_address":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skieste' .
                'ch A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4' .
                '-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","re' .
                'ason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","' .
                'first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.' .
                '36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country":' .
                '"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment Sy' .
                'stems, LLC","header_message":"This is a sample message for you","date_of_birth"' .
                ':"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone"' .
                ':"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists"' .
                ':1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de8f' .
                'bdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"acc' .
                'ount_vault":{"account_holder_name":"John Smith","account_number":"5454545454545' .
                '45","account_vault_api_id":"accountvaultabcd","accountvault_c1":"accountvault c' .
                'ustom 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountva' .
                'ult custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","street":"43155 Main Street STE 2310-C","phone":"' .
                '3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","id' .
                'entity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_' .
                'year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_' .
                'api_id":"previousaccountvault123456","previous_account_vault_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terms_agree"' .
                ':true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summary_status_id' .
                '":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,' .
                '"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"first_six":"7009' .
                '53","has_recurring":false,"last_four":"3657","modified_ts":1422040992,"payment_' .
                'method":"cc","ticket":null,"track_data":null},"created_user":{"account_number":' .
                '"5454545454545454","address":"43155 Main Street STE 2310-C","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","city":"Novi","company_nam' .
                'e":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_' .
                'of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@do' .
                'main.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John' .
                '","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_' .
                'phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_passw' .
                'ord":null,"state":"Michigan","terms_condition_code":"20220308","tz":"America/Ne' .
                'w_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type"' .
                ':"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fb' .
                'db0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user' .
                '_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040' .
                '992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","term' .
                's_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"' .
                '2019-03-11T10:38:26-0700"},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAAN' .
                'wAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJR' .
                'CKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6' .
                'GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURR' .
                'NMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY8' .
                '3zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUr' .
                'mr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT' .
                '647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6J' .
                'aLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2' .
                'yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmP' .
                'iY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU' .
                '53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/' .
                'Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYB' .
                'HBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040' .
                '992,"modified_ts":1422040992},"payment_schedule":["2021-12-01"],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2' .
                '":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09324' .
                '2bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","locati' .
                'on_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","loc' .
                'ation_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","na' .
                'me":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone' .
                '":"1021021209","recurring_notification_days_default":0,"tz":"America/New_York",' .
                '"parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAAD' .
                'F4"},"product_transaction":{"processor_version":"1_0_0","title":"My terminal","' .
                'payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,' .
                '"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},' .
                '"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_t' .
                'ip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true' .
                ',"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":t' .
                'rue,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,"' .
                'card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_diner' .
                's":true,"card_type_jcb":true,"invoice_location":true,"allow_partial_authorizati' .
                'on":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,"' .
                'auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,"' .
                'vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sale' .
                's_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_requir' .
                'e_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch' .
                '":null,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"' .
                'sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"' .
                'surcharge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":null,"cau_subscribe_t' .
                'ype_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_bil' .
                'ling_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_cr' .
                'eate":false,"accountvault_expire_notification_email_enable":false,"debit_allow_' .
                'void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_curre' .
                'ncy":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_com' .
                'pany_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts' .
                '":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"},"next_run_date_min":"2021-12-01","next_run_date_max":' .
                '"2021-12-01","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My term' .
                'inal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992}],"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My ter' .
                'minal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14' .
                '22040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008' .
                'be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_ru' .
                'n_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","usern' .
                'ame":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],"forecast"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","created_ts":14' .
                '22040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}]' .
                '}}'
            )))
            ->assert();
    }

    public function testTestPlaceOnHoldRecurringPayment()
    {
        // Parameters for the API call
        $recurringId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->placeOnHoldRecurringPayment($recurringId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Recurring","data":{"account_vault_id":"11e95f8ec39de8fbdb0a4f1a","act' .
                'ive":true,"description":"Description","end_date":"2021-12-01","installment_tota' .
                'l_count":20,"interval":1,"interval_type":"d","location_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","notification_days":2,"payment_method":"cc","product_transaction_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8fbdb0a4f1a","recurring_ap' .
                'i_id":"recurring1234abcd","start_date":"2021-12-01","status":"active","transact' .
                'ion_amount":3,"terms_agree":true,"terms_agree_ip":"192.168.0.10","recurring_c1"' .
                ':"recurring custom data 1","recurring_c2":"recurring custom data 2","recurring_' .
                'c3":"recurring custom data 3","send_to_proc_as_recur":true,"id":"11e95f8ec39de8' .
                'fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":1422040992,"modified_ts":' .
                '1422040992,"recurring_type_id":"i","log_emails":[{"subject":"Payment Receipt - ' .
                '12skiestech","body":"This email is being sent from a server.","source_address":' .
                '"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skieste' .
                'ch A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23b4' .
                '-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","re' .
                'ason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137","' .
                'first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":245.' .
                '36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country":' .
                '"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment Sy' .
                'stems, LLC","header_message":"This is a sample message for you","date_of_birth"' .
                ':"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phone"' .
                ':"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exists"' .
                ':1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","parent_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de8f' .
                'bdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"acc' .
                'ount_vault":{"account_holder_name":"John Smith","account_number":"5454545454545' .
                '45","account_vault_api_id":"accountvaultabcd","accountvault_c1":"accountvault c' .
                'ustom 1","accountvault_c2":"accountvault custom 2","accountvault_c3":"accountva' .
                'ult custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi","state":"Mi' .
                'chigan","postal_code":"48375","street":"43155 Main Street STE 2310-C","phone":"' .
                '3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":"123456","id' .
                'entity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":"8527","dob_' .
                'year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_account_vault_' .
                'api_id":"previousaccountvault123456","previous_account_vault_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","terms_agree"' .
                ':true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id":"11e95f8ec' .
                '39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summary_status_id' .
                '":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track_data":null,' .
                '"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"first_six":"7009' .
                '53","has_recurring":false,"last_four":"3657","modified_ts":1422040992,"payment_' .
                'method":"cc","ticket":null,"track_data":null},"created_user":{"account_number":' .
                '"5454545454545454","address":"43155 Main Street STE 2310-C","branding_domain_ur' .
                'l":"{branding_domain_url}","cell_phone":"3339998822","city":"Novi","company_nam' .
                'e":"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_' .
                'of_birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@do' .
                'main.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John' .
                '","last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_' .
                'phone":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_passw' .
                'ord":null,"state":"Michigan","terms_condition_code":"20220308","tz":"America/Ne' .
                'w_York","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type"' .
                ':"csv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fb' .
                'db0a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user' .
                '_hash_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","' .
                'status":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040' .
                '992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","term' .
                's_accepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"' .
                '2019-03-11T10:38:26-0700"},"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAAN' .
                'wAAAAsCAYAAAAOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJR' .
                'CKR+NxyD4OIXtaXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6' .
                'GngTgnNYVVW6WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURR' .
                'NMEu8A8FNrCzLm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY8' .
                '3zXOu6vnqfeQ/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUr' .
                'mr7/b4NLU3T9jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT' .
                '647T6aSr1UpFRPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6J' .
                'aLBYax7EmSXJ3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2' .
                'yCK4pCRUSPx+Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmP' .
                'iY03/fZXk7s1wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU' .
                '53kPb/9+SlRj9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/' .
                'Dz5tVcMDcERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYB' .
                'HBARYRHGDRX+EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040' .
                '992,"modified_ts":1422040992},"payment_schedule":["2021-12-01"],"location":{"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"' .
                'account_number":"5454545454545454","address":{"city":"Novi","state":"MI","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2' .
                '":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09324' .
                '2bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","locati' .
                'on_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","loc' .
                'ation_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","na' .
                'me":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone' .
                '":"1021021209","recurring_notification_days_default":0,"tz":"America/New_York",' .
                '"parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAAD' .
                'F4"},"product_transaction":{"processor_version":"1_0_0","title":"My terminal","' .
                'payment_method":"cc","processor":"zgate","mcc":"1111","tax_surcharge_config":2,' .
                '"partner":"standalone","location_id":"11e95f8ec39de8fbdb0a4f1a","surcharge":{},' .
                '"processor_data":{},"vt_clerk_number":true,"vt_billing_phone":true,"vt_enable_t' .
                'ip":true,"ach_allow_debit":true,"ach_allow_credit":true,"ach_allow_refund":true' .
                ',"vt_cvv":true,"vt_street":true,"vt_zip":true,"vt_order_num":true,"vt_enable":t' .
                'rue,"receipt_show_contact_name":true,"display_avs":true,"card_type_visa":true,"' .
                'card_type_mc":true,"card_type_disc":true,"card_type_amex":true,"card_type_diner' .
                's":true,"card_type_jcb":true,"invoice_location":true,"allow_partial_authorizati' .
                'on":true,"allow_recurring_partial_authorization":true,"auto_decline_cvv":true,"' .
                'auto_decline_street":true,"auto_decline_zip":true,"split_payments_allow":true,"' .
                'vt_show_custom_fields":true,"receipt_show_custom_fields":true,"vt_override_sale' .
                's_tax_allowed":true,"vt_enable_sales_tax":true,"vt_require_zip":true,"vt_requir' .
                'e_street":true,"auto_decline_cavv":true,"current_batch":34,"dup_check_per_batch' .
                '":null,"quick_invoice_allow":false,"level3_allow":false,"payfac_enable":false,"' .
                'sales_office_id":"11e95f8ec39de8fbdb0a4f1a","hosted_payment_page_allow":false,"' .
                'surcharge_id":"11e95f8ec39de8fbdb0a4f1a","level3_default":null,"cau_subscribe_t' .
                'ype_id":0,"location_billing_account_id":"11eb88b873980c64a21e5fd2","product_bil' .
                'ling_group_id":"nofees","account_number":"12345678","run_avs_on_accountvault_cr' .
                'eate":false,"accountvault_expire_notification_email_enable":false,"debit_allow_' .
                'void":false,"quick_invoice_text_to_pay":false,"sms_enable":false,"vt_show_curre' .
                'ncy":true,"receipt_show_currency":false,"allow_blind_refund":false,"vt_show_com' .
                'pany_name":false,"receipt_show_company_name":false,"bank_funded_only":false,"id' .
                '":"11e95f8ec39de8fbdb0a4f1a","active":true,"created_ts":1422040992,"modified_ts' .
                '":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a"},"next_run_date_min":"2021-12-01","next_run_date_max":' .
                '"2021-12-01","tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My term' .
                'inal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142' .
                '2040992}],"all_tags":[{"location_id":"11e95f8ec39de8fbdb0a4f1a","title":"My ter' .
                'minal","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14' .
                '22040992}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":14220409' .
                '92,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008' .
                'be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_ru' .
                'n_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","usern' .
                'ame":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],"forecast"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"Recurring ID","created_ts":14' .
                '22040992,"modified_ts":1422040992},"recurring_splits":[{"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","created_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}]' .
                '}}'
            )))
            ->assert();
    }
}
