<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\TokensController;
use FortisAPILib\Exceptions;

class TokensControllerTest extends BaseTestController
{
    /**
     * @var TokensController TokensController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTokensController();
    }

    public function testTestDeleteASingleTokenRecord()
    {
        // Parameters for the API call
        $tokenId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteASingleTokenRecord($tokenId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Token","data":{"account_holder_name":"John Smith","account_number":"5' .
                '45454545454545","account_vault_api_id":"accountvaultabcd","accountvault_c1":"ac' .
                'countvault custom 1","accountvault_c2":"accountvault custom 2","accountvault_c3' .
                '":"accountvault custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi"' .
                ',"state":"Michigan","postal_code":"48375","street":"43155 Main Street STE 2310-' .
                'C","phone":"3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":' .
                '"123456","identity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":' .
                '"8527","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_ac' .
                'count_vault_api_id":"previousaccountvault123456","previous_account_vault_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summa' .
                'ry_status_id":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track' .
                '_data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"firs' .
                't_six":"700953","has_recurring":false,"last_four":"3657","modified_ts":14220409' .
                '92,"payment_method":"cc","ticket":null,"track_data":null,"location":{"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"account' .
                '_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal_code"' .
                ':"48375","country":"US","street":"43155 Main Street STE 2310-C","street2":"4315' .
                '5 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","con' .
                'tact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb2","' .
                'default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","location_api_' .
                'id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c' .
                '1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sa' .
                'mple Company Headquarters","office_phone":"2481234567","office_ext_phone":"1021' .
                '021209","recurring_notification_days_default":0,"tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"c' .
                'ontact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332' .
                '","contact_api_id":"137","first_name":"John","last_name":"Smith","cell_phone":"' .
                '3339998822","balance":245.36,"address":{"city":"Novi","state":"Michigan","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C"},"compan' .
                'y_name":"Fortis Payment Systems, LLC","header_message":"This is a sample messag' .
                'e for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"' .
                '3339998822","office_phone":"3339998822","office_phone_ext":"5","header_message_' .
                'type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contac' .
                't_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.' .
                'com","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422' .
                '040992,"active":true},"transactions":[{"additional_amounts":[{"type":"cashback"' .
                ',"amount":10,"account_type":"credit","currency":840}],"billing_address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","street":"43155 Main Street ST' .
                'E 2310-C","phone":"3339998822"},"checkin_date":"2021-12-01","checkout_date":"20' .
                '21-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cust' .
                'om_data":{},"customer_id":"customerid","description":"some description","identi' .
                'ty_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"iia' .
                's_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","imag' .
                'e_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"' .
                'installment_number":1,"installment_count":1,"location_api_id":"location-api-id-' .
                'florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification_' .
                'email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number"' .
                ':"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":false' .
                ',"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sav' .
                'e_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"t' .
                'ags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"second' .
                'ary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_c' .
                '1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-da' .
                'ta-3","bank_funded_only_override":false,"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_holder_name":"smith","account_type":"checking","token_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"a' .
                'uth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_present":true,"ca' .
                'rd_present":true,"check_number":"8520748520963","customer_ip":"192.168.0.10","c' .
                'vv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203"' .
                ',"APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","T' .
                'VR":"0800008000"},"first_six":"545454","last_four":"5454","payment_method":"cc"' .
                ',"terminal_serial_number":"1234567890","transaction_settlement_status":null,"ch' .
                'arge_back_date":"2021-12-01","is_recurring":true,"notification_email_sent":"tru' .
                'e","par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":101,"transac' .
                'tion_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","void_date":"20' .
                '21-12-01","batch":"2","terms_agree":true,"response_message":null,"return_date":' .
                '"2021-12-01","trx_source_id":8}],"activeRecurrings":[{"account_vault_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"description":"Description","end_date":"2021' .
                '-12-01","installment_total_count":20,"interval":1,"interval_type":"d","location' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","pr' .
                'oduct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","s' .
                'tatus":"active","transaction_amount":3,"terms_agree":true,"terms_agree_ip":"192' .
                '.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurring c' .
                'ustom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":' .
                'true,"id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":' .
                '1422040992,"modified_ts":1422040992,"recurring_type_id":"i"}],"is_deletable":tr' .
                'ue,"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvk' .
                'lEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5M' .
                'wZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmn' .
                'gzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o' .
                '3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0Vz' .
                'HP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO62' .
                '0ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41' .
                'TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUp' .
                'oVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9Wqb' .
                'FRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKl' .
                'bDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsy' .
                'm+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBH' .
                'BARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAA' .
                'AAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992},"created_user":{"account_number":"5454545454545454","address":"43155 Main' .
                ' Street STE 2310-C","branding_domain_url":"{branding_domain_url}","cell_phone":' .
                '"3339998822","city":"Novi","company_name":"Fortis Payment Systems, LLC","contac' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home' .
                '_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","' .
                'office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_id"' .
                ':true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700"},"changelogs":' .
                '[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mo' .
                'del":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","ch' .
                'angelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"16436' .
                '16000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com",' .
                '"first_name":"Bob","last_name":"Fairview"}}],"account_vault_cau_logs":[{"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","a' .
                'ccount_vault_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a"}],"account_vault_cau_product_transactions":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI","po' .
                'stal_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","stre' .
                'et2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09' .
                '3242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","loc' .
                'ation_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","' .
                'location_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3",' .
                '"name":"Sample Company Headquarters","office_phone":"2481234567","office_ext_ph' .
                'one":"1021021209","recurring_notification_days_default":0,"tz":"America/New_Yor' .
                'k","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBC' .
                'AADF4"}]}}'
            )))
            ->assert();
    }

    public function testTestViewSingleTokenRecord()
    {
        // Parameters for the API call
        $tokenId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleTokenRecord($tokenId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"Token","data":{"account_holder_name":"John Smith","account_number":"5' .
                '45454545454545","account_vault_api_id":"accountvaultabcd","accountvault_c1":"ac' .
                'countvault custom 1","accountvault_c2":"accountvault custom 2","accountvault_c3' .
                '":"accountvault custom 3","ach_sec_code":"WEB","billing_address":{"city":"Novi"' .
                ',"state":"Michigan","postal_code":"48375","street":"43155 Main Street STE 2310-' .
                'C","phone":"3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","customer_id":' .
                '"123456","identity_verification":{"dl_state":"MI","dl_number":"1235567","ssn4":' .
                '"8527","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a","previous_ac' .
                'count_vault_api_id":"previousaccountvault123456","previous_account_vault_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"Test CC Account","id' .
                '":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":true,"cau_summa' .
                'ry_status_id":1,"created_ts":1422040992,"e_serial_number":"1234567890","e_track' .
                '_data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months":null,"firs' .
                't_six":"700953","has_recurring":false,"last_four":"3657","modified_ts":14220409' .
                '92,"payment_method":"cc","ticket":null,"track_data":null,"location":{"id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"account' .
                '_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal_code"' .
                ':"48375","country":"US","street":"43155 Main Street STE 2310-C","street2":"4315' .
                '5 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a","con' .
                'tact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242bb2","' .
                'default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec39de8fb' .
                'db0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","location_api_' .
                'id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","location_c' .
                '1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name":"Sa' .
                'mple Company Headquarters","office_phone":"2481234567","office_ext_phone":"1021' .
                '021209","recurring_notification_days_default":0,"tz":"America/New_York","parent' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"c' .
                'ontact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332' .
                '","contact_api_id":"137","first_name":"John","last_name":"Smith","cell_phone":"' .
                '3339998822","balance":245.36,"address":{"city":"Novi","state":"Michigan","posta' .
                'l_code":"48375","country":"US","street":"43155 Main Street STE 2310-C"},"compan' .
                'y_name":"Fortis Payment Systems, LLC","header_message":"This is a sample messag' .
                'e for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"' .
                '3339998822","office_phone":"3339998822","office_phone_ext":"5","header_message_' .
                'type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anything","contac' .
                't_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.' .
                'com","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422' .
                '040992,"active":true},"transactions":[{"additional_amounts":[{"type":"cashback"' .
                ',"amount":10,"account_type":"credit","currency":840}],"billing_address":{"city"' .
                ':"Novi","state":"Michigan","postal_code":"48375","street":"43155 Main Street ST' .
                'E 2310-C","phone":"3339998822"},"checkin_date":"2021-12-01","checkout_date":"20' .
                '21-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0a4f1a","cust' .
                'om_data":{},"customer_id":"customerid","description":"some description","identi' .
                'ty_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":"1980"},"iia' .
                's_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","imag' .
                'e_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","installment":true,"' .
                'installment_number":1,"installment_count":1,"location_api_id":"location-api-id-' .
                'florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"notification_' .
                'email_address":"johnsmith@smiths.com","order_number":"433659378839","po_number"' .
                ':"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recurring":false' .
                ',"recurring_number":1,"room_num":"303","room_rate":95,"save_account":false,"sav' .
                'e_account_title":"John Account","subtotal_amount":599,"surcharge_amount":100,"t' .
                'ags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amount":0,"second' .
                'ary_amount":0,"transaction_api_id":"transaction-payment-abcd123","transaction_c' .
                '1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3":"custom-da' .
                'ta-3","bank_funded_only_override":false,"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec39de8fbdb0a4f' .
                '1a","account_holder_name":"smith","account_type":"checking","token_id":"11e95f8' .
                'ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_amount":1,"a' .
                'uth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_present":true,"ca' .
                'rd_present":true,"check_number":"8520748520963","customer_ip":"192.168.0.10","c' .
                'vv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a0000000042203"' .
                ',"APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TSI":"e800","T' .
                'VR":"0800008000"},"first_six":"545454","last_four":"5454","payment_method":"cc"' .
                ',"terminal_serial_number":"1234567890","transaction_settlement_status":null,"ch' .
                'arge_back_date":"2021-12-01","is_recurring":true,"notification_email_sent":"tru' .
                'e","par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"recurring_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":101,"transac' .
                'tion_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","void_date":"20' .
                '21-12-01","batch":"2","terms_agree":true,"response_message":null,"return_date":' .
                '"2021-12-01","trx_source_id":8}],"activeRecurrings":[{"account_vault_id":"11e95' .
                'f8ec39de8fbdb0a4f1a","active":true,"description":"Description","end_date":"2021' .
                '-12-01","installment_total_count":20,"interval":1,"interval_type":"d","location' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_method":"cc","pr' .
                'oduct_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"2021-12-01","s' .
                'tatus":"active","transaction_amount":3,"terms_agree":true,"terms_agree_ip":"192' .
                '.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":"recurring c' .
                'ustom data 2","recurring_c3":"recurring custom data 3","send_to_proc_as_recur":' .
                'true,"id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","created_ts":' .
                '1422040992,"modified_ts":1422040992,"recurring_type_id":"i"}],"is_deletable":tr' .
                'ue,"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAAAOyNaYAAACvk' .
                'lEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIXtaXw2H3/5s5M' .
                'wZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6WCxURDTLsqmn' .
                'gzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCzLm5j68Q1Fx2o' .
                '3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ/bzHkgOIf0Vz' .
                'HP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9jVbTLcRnMO62' .
                '0ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpFRPf7ffveuq41' .
                'TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ3DD2v624rzUp' .
                'oVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+Okc/hfWI9Wqb' .
                'FRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1wR371z1zPnKl' .
                'bDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj9L8ALcJ/lNsy' .
                'm+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERxgEcEBFhEcYBH' .
                'BARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+EC0ah++pNrAA' .
                'AAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8ec39de8fbdb0a4f1' .
                'a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204' .
                '0992},"created_user":{"account_number":"5454545454545454","address":"43155 Main' .
                ' Street STE 2310-C","branding_domain_url":"{branding_domain_url}","cell_phone":' .
                '"3339998822","city":"Novi","company_name":"Fortis Payment Systems, LLC","contac' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","domain_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home' .
                '_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","' .
                'office_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","terms_cond' .
                'ition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashbo' .
                'ard","page_size":2,"report_export_type":"csv","process_method":"virtual_termina' .
                'l","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","use' .
                'r_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"pa' .
                'ssword":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_id"' .
                ':true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_lo' .
                'gin_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_i' .
                'p":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700"},"changelogs":' .
                '[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":"CREATE","mo' .
                'del":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbdb0a4f1a","ch' .
                'angelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_value":"16436' .
                '16000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@domain.com",' .
                '"first_name":"Bob","last_name":"Fairview"}}],"account_vault_cau_logs":[{"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","a' .
                'ccount_vault_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a"}],"account_vault_cau_product_transactions":[{' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI","po' .
                'stal_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","stre' .
                'et2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a' .
                '4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e09' .
                '3242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f' .
                '8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","loc' .
                'ation_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","' .
                'location_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3",' .
                '"name":"Sample Company Headquarters","office_phone":"2481234567","office_ext_ph' .
                'one":"1021021209","recurring_notification_days_default":0,"tz":"America/New_Yor' .
                'k","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBC' .
                'AADF4"}]}}'
            )))
            ->assert();
    }

    public function testTestListAllTokensRelated()
    {
        // Parameters for the API call
        $page = null;
        $sort = null;
        $filter = null;
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllTokensRelated($page, $sort, $filter, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"TokensCollection","list":[{"account_holder_name":"John Smith","accoun' .
                't_number":"545454545454545","account_vault_api_id":"accountvaultabcd","accountv' .
                'ault_c1":"accountvault custom 1","accountvault_c2":"accountvault custom 2","acc' .
                'ountvault_c3":"accountvault custom 3","ach_sec_code":"WEB","billing_address":{"' .
                'city":"Novi","state":"Michigan","postal_code":"48375","street":"43155 Main Stre' .
                'et STE 2310-C","phone":"3339998822"},"contact_id":"11e95f8ec39de8fbdb0a4f1a","c' .
                'ustomer_id":"123456","identity_verification":{"dl_state":"MI","dl_number":"1235' .
                '567","ssn4":"8527","dob_year":"1980"},"location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"previous_account_vault_api_id":"previousaccountvault123456","previous_account_' .
                'vault_id":"11e95f8ec39de8fbdb0a4f1a","previous_transaction_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","terms_agree":true,"terms_agree_ip":"192.168.0.10","title":"Test CC ' .
                'Account","id":"11e95f8ec39de8fbdb0a4f1a","account_type":"checking","active":tru' .
                'e,"cau_summary_status_id":1,"created_ts":1422040992,"e_serial_number":"12345678' .
                '90","e_track_data":null,"e_format":null,"e_keyed_data":null,"expiring_in_months' .
                '":null,"first_six":"700953","has_recurring":false,"last_four":"3657","modified_' .
                'ts":1422040992,"payment_method":"cc","ticket":null,"track_data":null,"location"' .
                ':{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040' .
                '992,"account_number":"5454545454545454","address":{"city":"Novi","state":"MI","' .
                'postal_code":"48375","country":"US","street":"43155 Main Street STE 2310-C","st' .
                'reet2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb' .
                '0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e' .
                '093242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","l' .
                'ocation_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4"' .
                ',"location_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3' .
                '","name":"Sample Company Headquarters","office_phone":"2481234567","office_ext_' .
                'phone":"1021021209","recurring_notification_days_default":0,"tz":"America/New_Y' .
                'ork","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34B' .
                'BCAADF4"},"contact":{"location_id":"11e95f8ec39de8fbdb0a4f1a","account_number":' .
                '"54545433332","contact_api_id":"137","first_name":"John","last_name":"Smith","c' .
                'ell_phone":"3339998822","balance":245.36,"address":{"city":"Novi","state":"Mich' .
                'igan","postal_code":"48375","country":"US","street":"43155 Main Street STE 2310' .
                '-C"},"company_name":"Fortis Payment Systems, LLC","header_message":"This is a s' .
                'ample message for you","date_of_birth":"2021-12-01","email_trx_receipt":true,"h' .
                'ome_phone":"3339998822","office_phone":"3339998822","office_phone_ext":"5","hea' .
                'der_message_type":0,"update_if_exists":1,"contact_c1":"any","contact_c2":"anyth' .
                'ing","contact_c3":"something","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"e' .
                'mail@domain.com","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modif' .
                'ied_ts":1422040992,"active":true},"transactions":[{"additional_amounts":[{"type' .
                '":"cashback","amount":10,"account_type":"credit","currency":840}],"billing_addr' .
                'ess":{"city":"Novi","state":"Michigan","postal_code":"48375","street":"43155 Ma' .
                'in Street STE 2310-C","phone":"3339998822"},"checkin_date":"2021-12-01","checko' .
                'ut_date":"2021-12-01","clerk_number":"AE1234","contact_id":"11e95f8ec39de8fbdb0' .
                'a4f1a","custom_data":{},"customer_id":"customerid","description":"some descript' .
                'ion","identity_verification":{"dl_state":"MI","dl_number":"1235567","dob_year":' .
                '"1980"},"iias_ind":1,"image_front":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29' .
                'kZWQ=","image_back":"U29tZVN0cmluZ09idmlvdXNseU5vdEJhc2U2NEVuY29kZWQ=","install' .
                'ment":true,"installment_number":1,"installment_count":1,"location_api_id":"loca' .
                'tion-api-id-florida-2","location_id":"11e95f8ec39de8fbdb0a4f1a","product_transa' .
                'ction_id":"11e95f8ec39de8fbdb0a4f1a","advance_deposit":false,"no_show":false,"n' .
                'otification_email_address":"johnsmith@smiths.com","order_number":"433659378839"' .
                ',"po_number":"555555553123","quick_invoice_id":"11e95f8ec39de8fbdb0a4f1a","recu' .
                'rring":false,"recurring_number":1,"room_num":"303","room_rate":95,"save_account' .
                '":false,"save_account_title":"John Account","subtotal_amount":599,"surcharge_am' .
                'ount":100,"tags":["Walk-in Customer"],"tax":0,"tip_amount":0,"transaction_amoun' .
                't":0,"secondary_amount":0,"transaction_api_id":"transaction-payment-abcd123","t' .
                'ransaction_c1":"custom-data-1","transaction_c2":"custom-data-2","transaction_c3' .
                '":"custom-data-3","bank_funded_only_override":false,"id":"11e95f8ec39de8fbdb0a4' .
                'f1a","created_ts":1422040992,"modified_ts":1422040992,"terminal_id":"11e95f8ec3' .
                '9de8fbdb0a4f1a","account_holder_name":"smith","account_type":"checking","token_' .
                'id":"11e95f8ec39de8fbdb0a4f1a","ach_identifier":"P","ach_sec_code":"C21","auth_' .
                'amount":1,"auth_code":"BR349K","avs":"BAD","avs_enhanced":"N","cardholder_prese' .
                'nt":true,"card_present":true,"check_number":"8520748520963","customer_ip":"192.' .
                '168.0.10","cvv_response":"N","entry_mode_id":"C","emv_receipt_data":{"AID":"a00' .
                '00000042203","APPLAB":"US Maestro","APPN":"US Maestro","CVM":"Pin Verified","TS' .
                'I":"e800","TVR":"0800008000"},"first_six":"545454","last_four":"5454","payment_' .
                'method":"cc","terminal_serial_number":"1234567890","transaction_settlement_stat' .
                'us":null,"charge_back_date":"2021-12-01","is_recurring":true,"notification_emai' .
                'l_sent":"true","par":"Q1J4Z28RKA1EBL470G9XYG90R5D3E","reason_code_id":1000,"rec' .
                'urring_id":"11e95f8ec39de8fbdb0a4f1a","settle_date":"2021-12-01","status_code":' .
                '101,"transaction_batch_id":"11e95f8ec39de8fbdb0a4f1a","verbiage":"APPROVED","vo' .
                'id_date":"2021-12-01","batch":"2","terms_agree":true,"response_message":null,"r' .
                'eturn_date":"2021-12-01","trx_source_id":8}],"activeRecurrings":[{"account_vaul' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","active":true,"description":"Description","end' .
                '_date":"2021-12-01","installment_total_count":20,"interval":1,"interval_type":"' .
                'd","location_id":"11e95f8ec39de8fbdb0a4f1a","notification_days":2,"payment_meth' .
                'od":"cc","product_transaction_id":"11e95f8ec39de8fbdb0a4f1a","recurring_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","recurring_api_id":"recurring1234abcd","start_date":"20' .
                '21-12-01","status":"active","transaction_amount":3,"terms_agree":true,"terms_ag' .
                'ree_ip":"192.168.0.10","recurring_c1":"recurring custom data 1","recurring_c2":' .
                '"recurring custom data 2","recurring_c3":"recurring custom data 3","send_to_pro' .
                'c_as_recur":true,"id":"11e95f8ec39de8fbdb0a4f1a","next_run_date":"2021-12-01","' .
                'created_ts":1422040992,"modified_ts":1422040992,"recurring_type_id":"i"}],"is_d' .
                'eletable":true,"signature":{"signature":"iVBORw0KGgoAAAANSUhEUgAAANwAAAAsCAYAAA' .
                'AOyNaYAAACvklEQVR4nO3bLZOqUBjA8ScaNxqNRiKRaCQaiXwEG7cRiUajH8FINBqJRCKR+NxyD4OIX' .
                'taXw2H3/5s5MwZ39rgz/zkvuKKqgar+YTAYnx/y7wUACwgOsIjgAIsIznFlWerlcpl6GngTgnNYVVW6' .
                'WCxURDTLsqmngzcgOMdtNhsVERURDYJA8zyfekp4AcE5oCgKzfN8cOvYNM1VdCKiURRNMEu8A8FNrCz' .
                'Lm5j68Q1Fx2o3TwTngCzLNAiCq6D6UTVNo0mS6NfXF+HNGME5or+KeZ7XxrVcLjWOY83zXOu6vnqfeQ' .
                '/bzHkgOIf0VzHP83Sz2eh6vW4D831fy7JsowvDsH1NdO4jOAfVdX0VXhRFWhSFRlHUrmr7/b4NLU3T9' .
                'jVbTLcRnMO620ezep1Op3bF832/3XIORQr3EJzjumc7E9HQBUoYhjdnPKJzD8E5xjyT647T6aSr1UpF' .
                'RPf7ffveuq41TdOHZzyicwvBTeBeVGEY3jwaGBrmWV3/Z82K1z/jca5zB8F9wFBQY6JaLBYax7EmSXJ' .
                '3DD2v624rzUpoVrsgCDjXOWRWwVVVNfUUrvTDGrNK3YsqTdNRn69pGs2y7NshssV0w2yCK4pCRUSPx+' .
                'Okc/hfWI9WqbFRPaMbYjc+s7ptt1uic8BsgsvzXEVED4fDR3/P2PPVUFifDOo7THxmPiY03/fZXk7s1' .
                'wR371z1zPnKlbDGuvc9TKKz78cE9yio3W436vbv1fOV6/oPx010/Ee5PbMLbrfbPRWU53kPb/9+SlRj' .
                '9L8ALcJ/lNsym+DO5/PTQaVpqnVdT/0RnGLOed0LlikvpH6L2QSnqoPX4QT1mu4FC3/Dz5tVcMDcERx' .
                'gEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGARwQEWERxgEcEBFhEcYBHBARYRHGDRX+' .
                'EC0ah++pNrAAAAAElFTkSuQmCC","resource":"Transaction","resource_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modifie' .
                'd_ts":1422040992},"created_user":{"account_number":"5454545454545454","address"' .
                ':"43155 Main Street STE 2310-C","branding_domain_url":"{branding_domain_url}","' .
                'cell_phone":"3339998822","city":"Novi","company_name":"Fortis Payment Systems, ' .
                'LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021-12-01","doma' .
                'in_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt' .
                '":true,"home_phone":"3339998822","first_name":"John","last_name":"Smith","local' .
                'e":"en-US","office_phone":"3339998822","office_ext_phone":"5","primary_location' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan"' .
                ',"terms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_p' .
                'age":"dashboard","page_size":2,"report_export_type":"csv","process_method":"vir' .
                'tual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user' .
                '_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_c' .
                'ode":100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts' .
                '":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"t' .
                'erms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700"},"' .
                'changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"action":' .
                '"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4","us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de8fbd' .
                'b0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","old_v' .
                'alue":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"email@' .
                'domain.com","first_name":"Bob","last_name":"Fairview"}}],"account_vault_cau_log' .
                's":[{"id":"11e95f8ec39de8fbdb0a4f1a","product_transaction_id":"11e95f8ec39de8fb' .
                'db0a4f1a","account_vault_id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"account_vault_cau_product_tran' .
                'sactions":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"account_number":"5454545454545454","address":{"city":"Novi","sta' .
                'te":"MI","postal_code":"48375","country":"US","street":"43155 Main Street STE 2' .
                '310-C","street2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8e' .
                'c39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e60' .
                '8a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company' .
                '_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339' .
                '998822","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE3' .
                '4BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"cus' .
                'tom data 3","name":"Sample Company Headquarters","office_phone":"2481234567","o' .
                'ffice_ext_phone":"1021021209","recurring_notification_days_default":0,"tz":"Ame' .
                'rica/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443' .
                'CADF4AE34BBCAADF4"}]}],"links":{"type":"Links","first":"/v1/endpoint?page[size]' .
                '=10&page[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5","las' .
                't":"/v1/endpoint?page[size]=10&page[number]=42"},"pagination":{"type":"Paginati' .
                'on","total_count":423,"page_count":42,"page_number":6,"page_size":10},"sort":{"' .
                'type":"Sorting","fields":[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }
}
