<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use FortisAPILib\Controllers\UsersController;
use FortisAPILib\Exceptions;

class UsersControllerTest extends BaseTestController
{
    /**
     * @var UsersController UsersController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getUsersController();
    }

    public function testTestCreateANewAPIKey()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createANewAPIKey($userId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(201)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(
                TestParam::object('{"type":"UserApiKey","data":{"user_api_key":"234bas8dfn8238f923w2"}}')
            ))
            ->assert();
    }

    public function testTestListAllUser()
    {
        // Parameters for the API call
        $page = null;
        $sort = null;
        $filter = null;
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->listAllUser($page, $sort, $filter, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"UsersCollection","list":[{"account_number":"5454545454545454","addres' .
                's":"43155 Main Street STE 2310-C","branding_domain_url":"{branding_domain_url}"' .
                ',"cell_phone":"3339998822","city":"Novi","company_name":"Fortis Payment Systems' .
                ', LLC","contact_id":"Sample contact ID","date_of_birth":"2021-12-01","domain_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":tru' .
                'e,"home_phone":"3339998822","first_name":"John","last_name":"Smith","locale":"e' .
                'n-US","office_phone":"3339998822","office_ext_phone":"5","primary_location_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","ter' .
                'ms_condition_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":' .
                '"dashboard","page_size":2,"report_export_type":"csv","process_method":"virtual_' .
                'terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name' .
                '}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":' .
                '100,"password":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","sta' .
                'tus_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"' .
                'last_login_ts":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"cre' .
                'ated_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_' .
                'agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","locati' .
                'ons":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":14' .
                '22040992,"account_number":"5454545454545454","address":{"city":"Novi","state":"' .
                'MI","postal_code":"48375","country":"US","street":"43155 Main Street STE 2310-C' .
                '","street2":"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de' .
                '8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default_ach":"11e608a7d5' .
                '15f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"333999882' .
                '2","location_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCA' .
                'ADF4","location_c1":"custom 1","location_c2":"custom 2","location_c3":"custom d' .
                'ata 3","name":"Sample Company Headquarters","office_phone":"2481234567","office' .
                '_ext_phone":"1021021209","recurring_notification_days_default":0,"tz":"America/' .
                'New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4' .
                'AE34BBCAADF4"}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts' .
                '":1422040992,"modified_ts":1422040992,"account_number":"5454545454545454","addr' .
                'ess":{"city":"Novi","state":"MI","postal_code":"48375","country":"US","street":' .
                '"43155 Main Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"brand' .
                'ing_domain_id":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":t' .
                'rue,"default_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e09224' .
                '2dda","developer_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email' .
                '@domain.com","fax":"3339998822","location_api_id":"location-111111","location_a' .
                'pi_key":"AE34BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"cust' .
                'om 2","location_c3":"custom data 3","name":"Sample Company Headquarters","offic' .
                'e_phone":"2481234567","office_ext_phone":"1021021209","recurring_notification_d' .
                'ays_default":0,"tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'ticket_hash_key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Paym' .
                'ent Receipt - 12skiestech","body":"This email is being sent from a server.","so' .
                'urce_address":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path"' .
                ':"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67b' .
                'cc530-e1dd23b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8f' .
                'bdb0a4f1a","reason_sent":"Contact Email","reason_model":"Transaction","reason_m' .
                'odel_id":"11e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster' .
                '.com>","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"lo' .
                'cation_id":"11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_a' .
                'pi_id":"137","first_name":"John","last_name":"Smith","cell_phone":"3339998822",' .
                '"balance":245.36,"address":{"city":"Novi","state":"Michigan","postal_code":"483' .
                '75","country":"US","street":"43155 Main Street STE 2310-C"},"company_name":"For' .
                'tis Payment Systems, LLC","header_message":"This is a sample message for you","' .
                'date_of_birth":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822",' .
                '"office_phone":"3339998822","office_phone_ext":"5","header_message_type":0,"upd' .
                'ate_if_exists":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"somet' .
                'hing","parent_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"acti' .
                've":true},"isDeletable":true,"active_notification_alerts":[{"location_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a","date_start":"2021-12-01 10:10:00","date_end":"2021-12-01' .
                ' 10:10:00","user_location":true,"user_contact":true,"include_children":true,"al' .
                'ert_type":1,"alert_type_id":1,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422' .
                '040992,"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","m' .
                'odified_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"location_users":[{"location_id":' .
                '"11e95f8ec39de8fbdb0a4f1a","user_id":"11e95f8ec39de8fbdb0a4f1a","location_api_i' .
                'd":null,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1' .
                '422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e9' .
                '5f8ec39de8fbdb0a4f1a"}],"auth_roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","au' .
                'th_role_code":110,"code":83931,"created_ts":1422040992,"modified_ts":1422040992' .
                ',"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de' .
                '8fbdb0a4f1a"}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422' .
                '040992,"action":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d' .
                '4008be9aba4","user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"nex' .
                't_run_ts","old_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","u' .
                'sername":"email@domain.com","first_name":"Bob","last_name":"Fairview"}}],"resou' .
                'rces":{"title":"My terminal","priv":null,"resource_name":"v2.addons.iframe.get"' .
                ',"id":5693,"last_used_date":1422040992,"created_ts":1422040992,"modified_ts":14' .
                '22040992},"domain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test ' .
                'Brand Domain Title 2","logo":"","support_email":"email@domain.com","allow_conta' .
                'ct_signup":true,"allow_contact_registration":true,"allow_contact_login":true,"r' .
                'egistration_fields":["account_number"],"company_name":null,"nav_color":null,"bu' .
                'tton_primary_color":null,"logo_background_color":null,"icon_background_color":n' .
                'ull,"menu_text_background_color":null,"menu_text_color":null,"right_menu_backgr' .
                'ound_color":null,"right_menu_text_color":null,"button_primary_text_color":null,' .
                '"nav_logo":null,"fav_icon":null,"aes_key":null,"help_text":null,"email_reply_to' .
                '":"email@domain.com","email":"email@domain.com","custom_javascript":null,"custo' .
                'm_theme":null,"custom_css":null,"contact_user_default_entry_page":"dashboard","' .
                'contact_user_default_auth_roles":[null],"id":"11e95f8ec39de8fbdb0a4f1a","create' .
                'd_ts":1422040992,"modified_ts":1422040992},"created_user":{"account_number":"54' .
                '54545454545454","address":"43155 Main Street STE 2310-C","branding_domain_url":' .
                '"{branding_domain_url}","cell_phone":"3339998822","city":"Novi","company_name":' .
                '"Fortis Payment Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_' .
                'birth":"2021-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domai' .
                'n.com","email_trx_receipt":true,"home_phone":"3339998822","first_name":"John","' .
                'last_name":"Smith","locale":"en-US","office_phone":"3339998822","office_ext_pho' .
                'ne":"5","primary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password' .
                '":null,"state":"Michigan","terms_condition_code":"20220308","tz":"America/New_Y' .
                'ork","ui_prefs":{"entry_page":"dashboard","page_size":2,"report_export_type":"c' .
                'sv","process_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0' .
                'a4f1a"},"username":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_ha' .
                'sh_key":null,"user_type_code":100,"password":null,"zip":"48375","location_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","sta' .
                'tus":true,"login_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992' .
                ',"modified_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_a' .
                'ccepted_ts":1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"201' .
                '9-03-11T10:38:26-0700"},"location_marketplaces":[{"location_id":"11e95f8ec39de8' .
                'fbdb0a4f1a","marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,' .
                '"user_id":"11e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":' .
                '{"id":"11e95f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts' .
                '":1422040992},"helppage":{"user_type_code":100,"body":"Sample Body","title":"Sa' .
                'mple Title","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"' .
                '11e95f8ec39de8fbdb0a4f1a"}}],"links":{"type":"Links","first":"/v1/endpoint?page' .
                '[size]=10&page[number]=1","previous":"/v1/endpoint?page[size]=10&page[number]=5' .
                '","last":"/v1/endpoint?page[size]=10&page[number]=42"},"pagination":{"type":"Pa' .
                'gination","total_count":423,"page_count":42,"page_number":6,"page_size":10},"so' .
                'rt":{"type":"Sorting","fields":[{"field":"last_name","order":"asc"}]}}'
            )))
            ->assert();
    }

    public function testTestDeleteAUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->deleteAUserRecord($userId);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(204)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","address":"43155 Ma' .
                'in Street STE 2310-C","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","city":"Novi","company_name":"Fortis Payment Systems, LLC","cont' .
                'act_id":"Sample contact ID","date_of_birth":"2021-12-01","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phon' .
                'e":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","offic' .
                'e_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","terms_condition' .
                '_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard",' .
                '"page_size":2,"report_export_type":"csv","process_method":"virtual_terminal","d' .
                'efault_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api' .
                '_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"passwor' .
                'd":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_id":true' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_t' .
                's":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"1' .
                '92.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","locations":[{"id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"ac' .
                'count_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal_' .
                'code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2":' .
                '"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","location' .
                '_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","locat' .
                'ion_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name' .
                '":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":' .
                '"1021021209","recurring_notification_days_default":0,"tz":"America/New_York","p' .
                'arent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAADF4' .
                '"}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992' .
                ',"modified_ts":1422040992,"account_number":"5454545454545454","address":{"city"' .
                ':"Novi","state":"MI","postal_code":"48375","country":"US","street":"43155 Main ' .
                'Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","devel' .
                'oper_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","recurring_notification_days_default"' .
                ':0,"tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_' .
                'key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payment Receipt ' .
                '- 12skiestech","body":"This email is being sent from a server.","source_address' .
                '":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skies' .
                'tech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23' .
                'b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'reason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137"' .
                ',"first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":24' .
                '5.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country' .
                '":"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"i' .
                'sDeletable":true,"active_notification_alerts":[{"location_id":"11e95f8ec39de8fb' .
                'db0a4f1a","date_start":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","' .
                'user_location":true,"user_contact":true,"include_children":true,"alert_type":1,' .
                '"alert_type_id":1,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","user_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a"}],"auth_roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code' .
                '":110,"code":83931,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                '}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"acti' .
                'on":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4"' .
                ',"user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","o' .
                'ld_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"em' .
                'ail@domain.com","first_name":"Bob","last_name":"Fairview"}}],"resources":{"titl' .
                'e":"My terminal","priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"' .
                'last_used_date":1422040992,"created_ts":1422040992,"modified_ts":1422040992},"d' .
                'omain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain' .
                ' Title 2","logo":"","support_email":"email@domain.com","allow_contact_signup":t' .
                'rue,"allow_contact_registration":true,"allow_contact_login":true,"registration_' .
                'fields":["account_number"],"company_name":null,"nav_color":null,"button_primary' .
                '_color":null,"logo_background_color":null,"icon_background_color":null,"menu_te' .
                'xt_background_color":null,"menu_text_color":null,"right_menu_background_color":' .
                'null,"right_menu_text_color":null,"button_primary_text_color":null,"nav_logo":n' .
                'ull,"fav_icon":null,"aes_key":null,"help_text":null,"email_reply_to":"email@dom' .
                'ain.com","email":"email@domain.com","custom_javascript":null,"custom_theme":nul' .
                'l,"custom_css":null,"contact_user_default_entry_page":"dashboard","contact_user' .
                '_default_auth_roles":[null],"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992},"created_user":{"account_number":"54545454545454' .
                '54","address":"43155 Main Street STE 2310-C","branding_domain_url":"{branding_d' .
                'omain_url}","cell_phone":"3339998822","city":"Novi","company_name":"Fortis Paym' .
                'ent Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021' .
                '-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","emai' .
                'l_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"' .
                'Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pri' .
                'mary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"stat' .
                'e":"Michigan","terms_condition_code":"20220308","tz":"America/New_York","ui_pre' .
                'fs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","process' .
                '_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"use' .
                'rname":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null' .
                ',"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"l' .
                'ogin_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":' .
                '1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:3' .
                '8:26-0700"},"location_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992' .
                '},"helppage":{"user_type_code":100,"body":"Sample Body","title":"Sample Title",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testTestViewSingleUserRecord()
    {
        // Parameters for the API call
        $userId = '11e95f8ec39de8fbdb0a4f1a';
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSingleUserRecord($userId, $expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","address":"43155 Ma' .
                'in Street STE 2310-C","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","city":"Novi","company_name":"Fortis Payment Systems, LLC","cont' .
                'act_id":"Sample contact ID","date_of_birth":"2021-12-01","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phon' .
                'e":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","offic' .
                'e_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","terms_condition' .
                '_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard",' .
                '"page_size":2,"report_export_type":"csv","process_method":"virtual_terminal","d' .
                'efault_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api' .
                '_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"passwor' .
                'd":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_id":true' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_t' .
                's":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"1' .
                '92.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","locations":[{"id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"ac' .
                'count_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal_' .
                'code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2":' .
                '"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","location' .
                '_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","locat' .
                'ion_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name' .
                '":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":' .
                '"1021021209","recurring_notification_days_default":0,"tz":"America/New_York","p' .
                'arent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAADF4' .
                '"}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992' .
                ',"modified_ts":1422040992,"account_number":"5454545454545454","address":{"city"' .
                ':"Novi","state":"MI","postal_code":"48375","country":"US","street":"43155 Main ' .
                'Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","devel' .
                'oper_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","recurring_notification_days_default"' .
                ':0,"tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_' .
                'key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payment Receipt ' .
                '- 12skiestech","body":"This email is being sent from a server.","source_address' .
                '":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skies' .
                'tech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23' .
                'b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'reason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137"' .
                ',"first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":24' .
                '5.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country' .
                '":"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"i' .
                'sDeletable":true,"active_notification_alerts":[{"location_id":"11e95f8ec39de8fb' .
                'db0a4f1a","date_start":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","' .
                'user_location":true,"user_contact":true,"include_children":true,"alert_type":1,' .
                '"alert_type_id":1,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","user_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a"}],"auth_roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code' .
                '":110,"code":83931,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                '}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"acti' .
                'on":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4"' .
                ',"user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","o' .
                'ld_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"em' .
                'ail@domain.com","first_name":"Bob","last_name":"Fairview"}}],"resources":{"titl' .
                'e":"My terminal","priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"' .
                'last_used_date":1422040992,"created_ts":1422040992,"modified_ts":1422040992},"d' .
                'omain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain' .
                ' Title 2","logo":"","support_email":"email@domain.com","allow_contact_signup":t' .
                'rue,"allow_contact_registration":true,"allow_contact_login":true,"registration_' .
                'fields":["account_number"],"company_name":null,"nav_color":null,"button_primary' .
                '_color":null,"logo_background_color":null,"icon_background_color":null,"menu_te' .
                'xt_background_color":null,"menu_text_color":null,"right_menu_background_color":' .
                'null,"right_menu_text_color":null,"button_primary_text_color":null,"nav_logo":n' .
                'ull,"fav_icon":null,"aes_key":null,"help_text":null,"email_reply_to":"email@dom' .
                'ain.com","email":"email@domain.com","custom_javascript":null,"custom_theme":nul' .
                'l,"custom_css":null,"contact_user_default_entry_page":"dashboard","contact_user' .
                '_default_auth_roles":[null],"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992},"created_user":{"account_number":"54545454545454' .
                '54","address":"43155 Main Street STE 2310-C","branding_domain_url":"{branding_d' .
                'omain_url}","cell_phone":"3339998822","city":"Novi","company_name":"Fortis Paym' .
                'ent Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021' .
                '-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","emai' .
                'l_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"' .
                'Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pri' .
                'mary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"stat' .
                'e":"Michigan","terms_condition_code":"20220308","tz":"America/New_York","ui_pre' .
                'fs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","process' .
                '_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"use' .
                'rname":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null' .
                ',"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"l' .
                'ogin_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":' .
                '1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:3' .
                '8:26-0700"},"location_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992' .
                '},"helppage":{"user_type_code":100,"body":"Sample Body","title":"Sample Title",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }

    public function testTestViewSelfRecord()
    {
        // Parameters for the API call
        $expand = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->viewSelfRecord($expand);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"type":"User","data":{"account_number":"5454545454545454","address":"43155 Ma' .
                'in Street STE 2310-C","branding_domain_url":"{branding_domain_url}","cell_phone' .
                '":"3339998822","city":"Novi","company_name":"Fortis Payment Systems, LLC","cont' .
                'act_id":"Sample contact ID","date_of_birth":"2021-12-01","domain_id":"11e95f8ec' .
                '39de8fbdb0a4f1a","email":"email@domain.com","email_trx_receipt":true,"home_phon' .
                'e":"3339998822","first_name":"John","last_name":"Smith","locale":"en-US","offic' .
                'e_phone":"3339998822","office_ext_phone":"5","primary_location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","requires_new_password":null,"state":"Michigan","terms_condition' .
                '_code":"20220308","tz":"America/New_York","ui_prefs":{"entry_page":"dashboard",' .
                '"page_size":2,"report_export_type":"csv","process_method":"virtual_terminal","d' .
                'efault_terminal":"11e95f8ec39de8fbdb0a4f1a"},"username":"{user_name}","user_api' .
                '_key":"234bas8dfn8238f923w2","user_hash_key":null,"user_type_code":100,"passwor' .
                'd":null,"zip":"48375","location_id":"11e95f8ec39de8fbdb0a4f1a","status_id":true' .
                ',"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"login_attempts":0,"last_login_t' .
                's":1422040992,"created_ts":1422040992,"modified_ts":1422040992,"created_user_id' .
                '":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":1422040992,"terms_agree_ip":"1' .
                '92.168.0.10","current_date_time":"2019-03-11T10:38:26-0700","locations":[{"id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"ac' .
                'count_number":"5454545454545454","address":{"city":"Novi","state":"MI","postal_' .
                'code":"48375","country":"US","street":"43155 Main Street STE 2310-C","street2":' .
                '"43155 Main Street STE 2310-C"},"branding_domain_id":"11e95f8ec39de8fbdb0a4f1a"' .
                ',"contact_email_trx_receipt_default":true,"default_ach":"11e608a7d515f1e093242b' .
                'b2","default_cc":"11e608a442a5f1e092242dda","developer_company_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","email_reply_to":"email@domain.com","fax":"3339998822","location' .
                '_api_id":"location-111111","location_api_key":"AE34BBCAADF4AE34BBCAADF4","locat' .
                'ion_c1":"custom 1","location_c2":"custom 2","location_c3":"custom data 3","name' .
                '":"Sample Company Headquarters","office_phone":"2481234567","office_ext_phone":' .
                '"1021021209","recurring_notification_days_default":0,"tz":"America/New_York","p' .
                'arent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_key":"A5F443CADF4AE34BBCAADF4' .
                '"}],"primary_location":{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992' .
                ',"modified_ts":1422040992,"account_number":"5454545454545454","address":{"city"' .
                ':"Novi","state":"MI","postal_code":"48375","country":"US","street":"43155 Main ' .
                'Street STE 2310-C","street2":"43155 Main Street STE 2310-C"},"branding_domain_i' .
                'd":"11e95f8ec39de8fbdb0a4f1a","contact_email_trx_receipt_default":true,"default' .
                '_ach":"11e608a7d515f1e093242bb2","default_cc":"11e608a442a5f1e092242dda","devel' .
                'oper_company_id":"11e95f8ec39de8fbdb0a4f1a","email_reply_to":"email@domain.com"' .
                ',"fax":"3339998822","location_api_id":"location-111111","location_api_key":"AE3' .
                '4BBCAADF4AE34BBCAADF4","location_c1":"custom 1","location_c2":"custom 2","locat' .
                'ion_c3":"custom data 3","name":"Sample Company Headquarters","office_phone":"24' .
                '81234567","office_ext_phone":"1021021209","recurring_notification_days_default"' .
                ':0,"tz":"America/New_York","parent_id":"11e95f8ec39de8fbdb0a4f1a","ticket_hash_' .
                'key":"A5F443CADF4AE34BBCAADF4"},"received_emails":[{"subject":"Payment Receipt ' .
                '- 12skiestech","body":"This email is being sent from a server.","source_address' .
                '":"\\"12skiestech A7t3qi\\" <noreply@zeamster.email>","return_path":"\\"12skies' .
                'tech A7t3qi\\" <noreply@zeamster.email>","provider_id":"0100017e67bcc530-e1dd23' .
                'b4-8a39-4a5b-8d5d-68d51c4c942f-000000","domain_id":"11e95f8ec39de8fbdb0a4f1a","' .
                'reason_sent":"Contact Email","reason_model":"Transaction","reason_model_id":"11' .
                'e95f8ec39de8fbdb0a4f1a","reply_to":"\\"Zeamster\\" <emma.p@zeamster.com>","id":' .
                '"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992}],"contact":{"location_id":"' .
                '11e95f8ec39de8fbdb0a4f1a","account_number":"54545433332","contact_api_id":"137"' .
                ',"first_name":"John","last_name":"Smith","cell_phone":"3339998822","balance":24' .
                '5.36,"address":{"city":"Novi","state":"Michigan","postal_code":"48375","country' .
                '":"US","street":"43155 Main Street STE 2310-C"},"company_name":"Fortis Payment ' .
                'Systems, LLC","header_message":"This is a sample message for you","date_of_birt' .
                'h":"2021-12-01","email_trx_receipt":true,"home_phone":"3339998822","office_phon' .
                'e":"3339998822","office_phone_ext":"5","header_message_type":0,"update_if_exist' .
                's":1,"contact_c1":"any","contact_c2":"anything","contact_c3":"something","paren' .
                't_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","id":"11e95f8ec39de' .
                '8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"active":true},"i' .
                'sDeletable":true,"active_notification_alerts":[{"location_id":"11e95f8ec39de8fb' .
                'db0a4f1a","date_start":"2021-12-01 10:10:00","date_end":"2021-12-01 10:10:00","' .
                'user_location":true,"user_contact":true,"include_children":true,"alert_type":1,' .
                '"alert_type_id":1,"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modi' .
                'fied_ts":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user' .
                '_id":"11e95f8ec39de8fbdb0a4f1a"}],"location_users":[{"location_id":"11e95f8ec39' .
                'de8fbdb0a4f1a","user_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"id"' .
                ':"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":1422040992,"c' .
                'reated_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fb' .
                'db0a4f1a"}],"auth_roles":[{"user_id":"11e95f8ec39de8fbdb0a4f1a","auth_role_code' .
                '":110,"code":83931,"created_ts":1422040992,"modified_ts":1422040992,"created_us' .
                'er_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39de8fbdb0a4f1a"' .
                '}],"changelogs":[{"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"acti' .
                'on":"CREATE","model":"TransactionRequest","model_id":"11ec829598f0d4008be9aba4"' .
                ',"user_id":"11e95f8ec39de8fbdb0a4f1a","changelog_details":[{"id":"11e95f8ec39de' .
                '8fbdb0a4f1a","changelog_id":"11e95f8ec39de8fbdb0a4f1a","field":"next_run_ts","o' .
                'ld_value":"1643616000"}],"user":{"id":"11e95f8ec39de8fbdb0a4f1a","username":"em' .
                'ail@domain.com","first_name":"Bob","last_name":"Fairview"}}],"resources":{"titl' .
                'e":"My terminal","priv":null,"resource_name":"v2.addons.iframe.get","id":5693,"' .
                'last_used_date":1422040992,"created_ts":1422040992,"modified_ts":1422040992},"d' .
                'omain":{"url":"fortispayrbyn9y.sandbox.zeamster.com","title":"Test Brand Domain' .
                ' Title 2","logo":"","support_email":"email@domain.com","allow_contact_signup":t' .
                'rue,"allow_contact_registration":true,"allow_contact_login":true,"registration_' .
                'fields":["account_number"],"company_name":null,"nav_color":null,"button_primary' .
                '_color":null,"logo_background_color":null,"icon_background_color":null,"menu_te' .
                'xt_background_color":null,"menu_text_color":null,"right_menu_background_color":' .
                'null,"right_menu_text_color":null,"button_primary_text_color":null,"nav_logo":n' .
                'ull,"fav_icon":null,"aes_key":null,"help_text":null,"email_reply_to":"email@dom' .
                'ain.com","email":"email@domain.com","custom_javascript":null,"custom_theme":nul' .
                'l,"custom_css":null,"contact_user_default_entry_page":"dashboard","contact_user' .
                '_default_auth_roles":[null],"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204' .
                '0992,"modified_ts":1422040992},"created_user":{"account_number":"54545454545454' .
                '54","address":"43155 Main Street STE 2310-C","branding_domain_url":"{branding_d' .
                'omain_url}","cell_phone":"3339998822","city":"Novi","company_name":"Fortis Paym' .
                'ent Systems, LLC","contact_id":"11e95f8ec39de8fbdb0a4f1a","date_of_birth":"2021' .
                '-12-01","domain_id":"11e95f8ec39de8fbdb0a4f1a","email":"email@domain.com","emai' .
                'l_trx_receipt":true,"home_phone":"3339998822","first_name":"John","last_name":"' .
                'Smith","locale":"en-US","office_phone":"3339998822","office_ext_phone":"5","pri' .
                'mary_location_id":"11e95f8ec39de8fbdb0a4f1a","requires_new_password":null,"stat' .
                'e":"Michigan","terms_condition_code":"20220308","tz":"America/New_York","ui_pre' .
                'fs":{"entry_page":"dashboard","page_size":2,"report_export_type":"csv","process' .
                '_method":"virtual_terminal","default_terminal":"11e95f8ec39de8fbdb0a4f1a"},"use' .
                'rname":"{user_name}","user_api_key":"234bas8dfn8238f923w2","user_hash_key":null' .
                ',"user_type_code":100,"password":null,"zip":"48375","location_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a","status_id":true,"id":"11e95f8ec39de8fbdb0a4f1a","status":true,"l' .
                'ogin_attempts":0,"last_login_ts":1422040992,"created_ts":1422040992,"modified_t' .
                's":1422040992,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","terms_accepted_ts":' .
                '1422040992,"terms_agree_ip":"192.168.0.10","current_date_time":"2019-03-11T10:3' .
                '8:26-0700"},"location_marketplaces":[{"location_id":"11e95f8ec39de8fbdb0a4f1a",' .
                '"marketplace_id":"11e95f8ec39de8fbdb0a4f1a","location_api_id":null,"user_id":"1' .
                '1e95f8ec39de8fbdb0a4f1a","id":"11e95f8ec39de8fbdb0a4f1a","created_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a"}],"email_blacklist":{"id":"11e95' .
                'f8ec39de8fbdb0a4f1a","isBlacklisted":true,"detail":true,"created_ts":1422040992' .
                '},"helppage":{"user_type_code":100,"body":"Sample Body","title":"Sample Title",' .
                '"id":"11e95f8ec39de8fbdb0a4f1a","created_ts":1422040992,"modified_ts":142204099' .
                '2,"created_user_id":"11e95f8ec39de8fbdb0a4f1a","modified_user_id":"11e95f8ec39d' .
                'e8fbdb0a4f1a"}}}'
            )))
            ->assert();
    }
}
