<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

class Data20 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $userApiKey;

    /**
     * @param string $userApiKey
     */
    public function __construct(string $userApiKey)
    {
        $this->userApiKey = $userApiKey;
    }

    /**
     * Returns User Api Key.
     * User Api Key
     */
    public function getUserApiKey(): string
    {
        return $this->userApiKey;
    }

    /**
     * Sets User Api Key.
     * User Api Key
     *
     * @required
     * @maps user_api_key
     */
    public function setUserApiKey(string $userApiKey): void
    {
        $this->userApiKey = $userApiKey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['user_api_key'] = $this->userApiKey;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
