<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

class Joi implements \JsonSerializable
{
    /**
     * @var Conditions|null
     */
    private $conditions;

    /**
     * Returns Conditions.
     */
    public function getConditions(): ?Conditions
    {
        return $this->conditions;
    }

    /**
     * Sets Conditions.
     *
     * @maps conditions
     */
    public function setConditions(?Conditions $conditions): void
    {
        $this->conditions = $conditions;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->conditions)) {
            $json['conditions'] = $this->conditions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
