<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

class List5 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $locationId;

    /**
     * @var string
     */
    private $ccProductTransactionId;

    /**
     * @var string
     */
    private $email;

    /**
     * @var float
     */
    private $amountDue;

    /**
     * @var array
     */
    private $locationApiId = [];

    /**
     * @var array
     */
    private $contactId = [];

    /**
     * @var array
     */
    private $contactApiId = [];

    /**
     * @var array
     */
    private $paylinkApiId = [];

    /**
     * @var array
     */
    private $achProductTransactionId = [];

    /**
     * @var array
     */
    private $expireDate = [];

    /**
     * @var bool|null
     */
    private $displayProductTransactionReceiptDetails;

    /**
     * @var bool|null
     */
    private $displayBillingFields;

    /**
     * @var array
     */
    private $deliveryMethod = [];

    /**
     * @var array
     */
    private $cellPhone = [];

    /**
     * @var array
     */
    private $description = [];

    /**
     * @var string
     */
    private $id;

    /**
     * @var bool|null
     */
    private $statusId;

    /**
     * @var bool|null
     */
    private $active;

    /**
     * @var int
     */
    private $createdTs;

    /**
     * @var int
     */
    private $modifiedTs;

    /**
     * @var array
     */
    private $createdUserId = [];

    /**
     * @var array
     */
    private $modifiedUserId = [];

    /**
     * @param string $locationId
     * @param string $ccProductTransactionId
     * @param string $email
     * @param float $amountDue
     * @param string $id
     * @param int $createdTs
     * @param int $modifiedTs
     */
    public function __construct(
        string $locationId,
        string $ccProductTransactionId,
        string $email,
        float $amountDue,
        string $id,
        int $createdTs,
        int $modifiedTs
    ) {
        $this->locationId = $locationId;
        $this->ccProductTransactionId = $ccProductTransactionId;
        $this->email = $email;
        $this->amountDue = $amountDue;
        $this->id = $id;
        $this->createdTs = $createdTs;
        $this->modifiedTs = $modifiedTs;
    }

    /**
     * Returns Location Id.
     * Location ID
     */
    public function getLocationId(): string
    {
        return $this->locationId;
    }

    /**
     * Sets Location Id.
     * Location ID
     *
     * @required
     * @maps location_id
     */
    public function setLocationId(string $locationId): void
    {
        $this->locationId = $locationId;
    }

    /**
     * Returns Cc Product Transaction Id.
     * cc_product_transaction_id
     */
    public function getCcProductTransactionId(): string
    {
        return $this->ccProductTransactionId;
    }

    /**
     * Sets Cc Product Transaction Id.
     * cc_product_transaction_id
     *
     * @required
     * @maps cc_product_transaction_id
     */
    public function setCcProductTransactionId(string $ccProductTransactionId): void
    {
        $this->ccProductTransactionId = $ccProductTransactionId;
    }

    /**
     * Returns Email.
     * Email
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * Email
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Amount Due.
     * Amount Due
     */
    public function getAmountDue(): float
    {
        return $this->amountDue;
    }

    /**
     * Sets Amount Due.
     * Amount Due
     *
     * @required
     * @maps amount_due
     */
    public function setAmountDue(float $amountDue): void
    {
        $this->amountDue = $amountDue;
    }

    /**
     * Returns Location Api Id.
     * Location Api Id
     */
    public function getLocationApiId(): ?string
    {
        if (count($this->locationApiId) == 0) {
            return null;
        }
        return $this->locationApiId['value'];
    }

    /**
     * Sets Location Api Id.
     * Location Api Id
     *
     * @maps location_api_id
     */
    public function setLocationApiId(?string $locationApiId): void
    {
        $this->locationApiId['value'] = $locationApiId;
    }

    /**
     * Unsets Location Api Id.
     * Location Api Id
     */
    public function unsetLocationApiId(): void
    {
        $this->locationApiId = [];
    }

    /**
     * Returns Contact Id.
     * Contact Id
     */
    public function getContactId(): ?string
    {
        if (count($this->contactId) == 0) {
            return null;
        }
        return $this->contactId['value'];
    }

    /**
     * Sets Contact Id.
     * Contact Id
     *
     * @maps contact_id
     */
    public function setContactId(?string $contactId): void
    {
        $this->contactId['value'] = $contactId;
    }

    /**
     * Unsets Contact Id.
     * Contact Id
     */
    public function unsetContactId(): void
    {
        $this->contactId = [];
    }

    /**
     * Returns Contact Api Id.
     * Contact Api Id
     */
    public function getContactApiId(): ?string
    {
        if (count($this->contactApiId) == 0) {
            return null;
        }
        return $this->contactApiId['value'];
    }

    /**
     * Sets Contact Api Id.
     * Contact Api Id
     *
     * @maps contact_api_id
     */
    public function setContactApiId(?string $contactApiId): void
    {
        $this->contactApiId['value'] = $contactApiId;
    }

    /**
     * Unsets Contact Api Id.
     * Contact Api Id
     */
    public function unsetContactApiId(): void
    {
        $this->contactApiId = [];
    }

    /**
     * Returns Paylink Api Id.
     * Paylinke Api Id
     */
    public function getPaylinkApiId(): ?string
    {
        if (count($this->paylinkApiId) == 0) {
            return null;
        }
        return $this->paylinkApiId['value'];
    }

    /**
     * Sets Paylink Api Id.
     * Paylinke Api Id
     *
     * @maps paylink_api_id
     */
    public function setPaylinkApiId(?string $paylinkApiId): void
    {
        $this->paylinkApiId['value'] = $paylinkApiId;
    }

    /**
     * Unsets Paylink Api Id.
     * Paylinke Api Id
     */
    public function unsetPaylinkApiId(): void
    {
        $this->paylinkApiId = [];
    }

    /**
     * Returns Ach Product Transaction Id.
     * Ach Product Transaction Id
     */
    public function getAchProductTransactionId(): ?string
    {
        if (count($this->achProductTransactionId) == 0) {
            return null;
        }
        return $this->achProductTransactionId['value'];
    }

    /**
     * Sets Ach Product Transaction Id.
     * Ach Product Transaction Id
     *
     * @maps ach_product_transaction_id
     */
    public function setAchProductTransactionId(?string $achProductTransactionId): void
    {
        $this->achProductTransactionId['value'] = $achProductTransactionId;
    }

    /**
     * Unsets Ach Product Transaction Id.
     * Ach Product Transaction Id
     */
    public function unsetAchProductTransactionId(): void
    {
        $this->achProductTransactionId = [];
    }

    /**
     * Returns Expire Date.
     * Expire Date
     */
    public function getExpireDate(): ?string
    {
        if (count($this->expireDate) == 0) {
            return null;
        }
        return $this->expireDate['value'];
    }

    /**
     * Sets Expire Date.
     * Expire Date
     *
     * @maps expire_date
     */
    public function setExpireDate(?string $expireDate): void
    {
        $this->expireDate['value'] = $expireDate;
    }

    /**
     * Unsets Expire Date.
     * Expire Date
     */
    public function unsetExpireDate(): void
    {
        $this->expireDate = [];
    }

    /**
     * Returns Display Product Transaction Receipt Details.
     * Display Product Transaction Receipt Details
     */
    public function getDisplayProductTransactionReceiptDetails(): ?bool
    {
        return $this->displayProductTransactionReceiptDetails;
    }

    /**
     * Sets Display Product Transaction Receipt Details.
     * Display Product Transaction Receipt Details
     *
     * @maps display_product_transaction_receipt_details
     */
    public function setDisplayProductTransactionReceiptDetails(?bool $displayProductTransactionReceiptDetails): void
    {
        $this->displayProductTransactionReceiptDetails = $displayProductTransactionReceiptDetails;
    }

    /**
     * Returns Display Billing Fields.
     * Display Billing Fields
     */
    public function getDisplayBillingFields(): ?bool
    {
        return $this->displayBillingFields;
    }

    /**
     * Sets Display Billing Fields.
     * Display Billing Fields
     *
     * @maps display_billing_fields
     */
    public function setDisplayBillingFields(?bool $displayBillingFields): void
    {
        $this->displayBillingFields = $displayBillingFields;
    }

    /**
     * Returns Delivery Method.
     * Delivery Method
     * >0 - Do not send
     * >
     * >1 - Email
     * >
     * >2 - SMS
     * >
     * >3 - Both
     * >
     */
    public function getDeliveryMethod(): ?int
    {
        if (count($this->deliveryMethod) == 0) {
            return null;
        }
        return $this->deliveryMethod['value'];
    }

    /**
     * Sets Delivery Method.
     * Delivery Method
     * >0 - Do not send
     * >
     * >1 - Email
     * >
     * >2 - SMS
     * >
     * >3 - Both
     * >
     *
     * @maps delivery_method
     * @factory \FortisAPILib\Models\DeliveryMethodEnum::checkValue
     */
    public function setDeliveryMethod(?int $deliveryMethod): void
    {
        $this->deliveryMethod['value'] = $deliveryMethod;
    }

    /**
     * Unsets Delivery Method.
     * Delivery Method
     * >0 - Do not send
     * >
     * >1 - Email
     * >
     * >2 - SMS
     * >
     * >3 - Both
     * >
     */
    public function unsetDeliveryMethod(): void
    {
        $this->deliveryMethod = [];
    }

    /**
     * Returns Cell Phone.
     * Cell Phone
     */
    public function getCellPhone(): ?string
    {
        if (count($this->cellPhone) == 0) {
            return null;
        }
        return $this->cellPhone['value'];
    }

    /**
     * Sets Cell Phone.
     * Cell Phone
     *
     * @maps cell_phone
     */
    public function setCellPhone(?string $cellPhone): void
    {
        $this->cellPhone['value'] = $cellPhone;
    }

    /**
     * Unsets Cell Phone.
     * Cell Phone
     */
    public function unsetCellPhone(): void
    {
        $this->cellPhone = [];
    }

    /**
     * Returns Description.
     * Description
     */
    public function getDescription(): ?string
    {
        if (count($this->description) == 0) {
            return null;
        }
        return $this->description['value'];
    }

    /**
     * Sets Description.
     * Description
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description['value'] = $description;
    }

    /**
     * Unsets Description.
     * Description
     */
    public function unsetDescription(): void
    {
        $this->description = [];
    }

    /**
     * Returns Id.
     * Paylink Id
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Paylink Id
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Status Id.
     * Status Id
     */
    public function getStatusId(): ?bool
    {
        return $this->statusId;
    }

    /**
     * Sets Status Id.
     * Status Id
     *
     * @maps status_id
     */
    public function setStatusId(?bool $statusId): void
    {
        $this->statusId = $statusId;
    }

    /**
     * Returns Active.
     * Active
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     * Active
     *
     * @maps active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Returns Created Ts.
     * Created Time Stamp
     */
    public function getCreatedTs(): int
    {
        return $this->createdTs;
    }

    /**
     * Sets Created Ts.
     * Created Time Stamp
     *
     * @required
     * @maps created_ts
     */
    public function setCreatedTs(int $createdTs): void
    {
        $this->createdTs = $createdTs;
    }

    /**
     * Returns Modified Ts.
     * Modified Time Stamp
     */
    public function getModifiedTs(): int
    {
        return $this->modifiedTs;
    }

    /**
     * Sets Modified Ts.
     * Modified Time Stamp
     *
     * @required
     * @maps modified_ts
     */
    public function setModifiedTs(int $modifiedTs): void
    {
        $this->modifiedTs = $modifiedTs;
    }

    /**
     * Returns Created User Id.
     * User ID Created the register
     */
    public function getCreatedUserId(): ?string
    {
        if (count($this->createdUserId) == 0) {
            return null;
        }
        return $this->createdUserId['value'];
    }

    /**
     * Sets Created User Id.
     * User ID Created the register
     *
     * @maps created_user_id
     */
    public function setCreatedUserId(?string $createdUserId): void
    {
        $this->createdUserId['value'] = $createdUserId;
    }

    /**
     * Unsets Created User Id.
     * User ID Created the register
     */
    public function unsetCreatedUserId(): void
    {
        $this->createdUserId = [];
    }

    /**
     * Returns Modified User Id.
     * Last User ID that updated the register
     */
    public function getModifiedUserId(): ?string
    {
        if (count($this->modifiedUserId) == 0) {
            return null;
        }
        return $this->modifiedUserId['value'];
    }

    /**
     * Sets Modified User Id.
     * Last User ID that updated the register
     *
     * @maps modified_user_id
     */
    public function setModifiedUserId(?string $modifiedUserId): void
    {
        $this->modifiedUserId['value'] = $modifiedUserId;
    }

    /**
     * Unsets Modified User Id.
     * Last User ID that updated the register
     */
    public function unsetModifiedUserId(): void
    {
        $this->modifiedUserId = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['location_id']                                     = $this->locationId;
        $json['cc_product_transaction_id']                       = $this->ccProductTransactionId;
        $json['email']                                           = $this->email;
        $json['amount_due']                                      = $this->amountDue;
        if (!empty($this->locationApiId)) {
            $json['location_api_id']                             = $this->locationApiId['value'];
        }
        if (!empty($this->contactId)) {
            $json['contact_id']                                  = $this->contactId['value'];
        }
        if (!empty($this->contactApiId)) {
            $json['contact_api_id']                              = $this->contactApiId['value'];
        }
        if (!empty($this->paylinkApiId)) {
            $json['paylink_api_id']                              = $this->paylinkApiId['value'];
        }
        if (!empty($this->achProductTransactionId)) {
            $json['ach_product_transaction_id']                  = $this->achProductTransactionId['value'];
        }
        if (!empty($this->expireDate)) {
            $json['expire_date']                                 = $this->expireDate['value'];
        }
        if (isset($this->displayProductTransactionReceiptDetails)) {
            $json['display_product_transaction_receipt_details'] = $this->displayProductTransactionReceiptDetails;
        }
        if (isset($this->displayBillingFields)) {
            $json['display_billing_fields']                      = $this->displayBillingFields;
        }
        if (!empty($this->deliveryMethod)) {
            $json['delivery_method']                             =
                DeliveryMethodEnum::checkValue(
                    $this->deliveryMethod['value']
                );
        }
        if (!empty($this->cellPhone)) {
            $json['cell_phone']                                  = $this->cellPhone['value'];
        }
        if (!empty($this->description)) {
            $json['description']                                 = $this->description['value'];
        }
        $json['id']                                              = $this->id;
        if (isset($this->statusId)) {
            $json['status_id']                                   = $this->statusId;
        }
        if (isset($this->active)) {
            $json['active']                                      = $this->active;
        }
        $json['created_ts']                                      = $this->createdTs;
        $json['modified_ts']                                     = $this->modifiedTs;
        if (!empty($this->createdUserId)) {
            $json['created_user_id']                             = $this->createdUserId['value'];
        }
        if (!empty($this->modifiedUserId)) {
            $json['modified_user_id']                            = $this->modifiedUserId['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
