<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

/**
 * You can use any `field_name` from this endpoint results, and you can combine more than one field for
 * more complex sorting. You can use one of the following methods:
 * >/endpoint?sort={ "field_name": "asc", "field_name2": "desc" }
 * >
 * >/endpoint?sort[field_name]=asc&sort[field_name2]=desc
 * >
 */
class Sort17 implements \JsonSerializable
{
    /**
     * @var array|null
     */
    private $id;

    /**
     * @var array|null
     */
    private $createdTs;

    /**
     * @var array|null
     */
    private $modifiedTs;

    /**
     * @var array|null
     */
    private $accountNumber;

    /**
     * @var array|null
     */
    private $address;

    /**
     * @var array|null
     */
    private $brandingDomainId;

    /**
     * @var array|null
     */
    private $contactEmailTrxReceiptDefault;

    /**
     * @var array|null
     */
    private $defaultAch;

    /**
     * @var array|null
     */
    private $defaultCc;

    /**
     * @var array|null
     */
    private $developerCompanyId;

    /**
     * @var array|null
     */
    private $emailReplyTo;

    /**
     * @var array|null
     */
    private $fax;

    /**
     * @var array|null
     */
    private $locationApiId;

    /**
     * @var array|null
     */
    private $locationApiKey;

    /**
     * @var array|null
     */
    private $locationC1;

    /**
     * @var array|null
     */
    private $locationC2;

    /**
     * @var array|null
     */
    private $locationC3;

    /**
     * @var array|null
     */
    private $name;

    /**
     * @var array|null
     */
    private $officePhone;

    /**
     * @var array|null
     */
    private $officeExtPhone;

    /**
     * @var array|null
     */
    private $recurringNotificationDaysDefault;

    /**
     * @var array|null
     */
    private $tz;

    /**
     * @var array|null
     */
    private $relationship;

    /**
     * Returns Id.
     */
    public function getId(): ?array
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?array $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created Ts.
     */
    public function getCreatedTs(): ?array
    {
        return $this->createdTs;
    }

    /**
     * Sets Created Ts.
     *
     * @maps created_ts
     */
    public function setCreatedTs(?array $createdTs): void
    {
        $this->createdTs = $createdTs;
    }

    /**
     * Returns Modified Ts.
     */
    public function getModifiedTs(): ?array
    {
        return $this->modifiedTs;
    }

    /**
     * Sets Modified Ts.
     *
     * @maps modified_ts
     */
    public function setModifiedTs(?array $modifiedTs): void
    {
        $this->modifiedTs = $modifiedTs;
    }

    /**
     * Returns Account Number.
     */
    public function getAccountNumber(): ?array
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     *
     * @maps account_number
     */
    public function setAccountNumber(?array $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?array
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?array $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Branding Domain Id.
     */
    public function getBrandingDomainId(): ?array
    {
        return $this->brandingDomainId;
    }

    /**
     * Sets Branding Domain Id.
     *
     * @maps branding_domain_id
     */
    public function setBrandingDomainId(?array $brandingDomainId): void
    {
        $this->brandingDomainId = $brandingDomainId;
    }

    /**
     * Returns Contact Email Trx Receipt Default.
     */
    public function getContactEmailTrxReceiptDefault(): ?array
    {
        return $this->contactEmailTrxReceiptDefault;
    }

    /**
     * Sets Contact Email Trx Receipt Default.
     *
     * @maps contact_email_trx_receipt_default
     */
    public function setContactEmailTrxReceiptDefault(?array $contactEmailTrxReceiptDefault): void
    {
        $this->contactEmailTrxReceiptDefault = $contactEmailTrxReceiptDefault;
    }

    /**
     * Returns Default Ach.
     */
    public function getDefaultAch(): ?array
    {
        return $this->defaultAch;
    }

    /**
     * Sets Default Ach.
     *
     * @maps default_ach
     */
    public function setDefaultAch(?array $defaultAch): void
    {
        $this->defaultAch = $defaultAch;
    }

    /**
     * Returns Default Cc.
     */
    public function getDefaultCc(): ?array
    {
        return $this->defaultCc;
    }

    /**
     * Sets Default Cc.
     *
     * @maps default_cc
     */
    public function setDefaultCc(?array $defaultCc): void
    {
        $this->defaultCc = $defaultCc;
    }

    /**
     * Returns Developer Company Id.
     */
    public function getDeveloperCompanyId(): ?array
    {
        return $this->developerCompanyId;
    }

    /**
     * Sets Developer Company Id.
     *
     * @maps developer_company_id
     */
    public function setDeveloperCompanyId(?array $developerCompanyId): void
    {
        $this->developerCompanyId = $developerCompanyId;
    }

    /**
     * Returns Email Reply To.
     */
    public function getEmailReplyTo(): ?array
    {
        return $this->emailReplyTo;
    }

    /**
     * Sets Email Reply To.
     *
     * @maps email_reply_to
     */
    public function setEmailReplyTo(?array $emailReplyTo): void
    {
        $this->emailReplyTo = $emailReplyTo;
    }

    /**
     * Returns Fax.
     */
    public function getFax(): ?array
    {
        return $this->fax;
    }

    /**
     * Sets Fax.
     *
     * @maps fax
     */
    public function setFax(?array $fax): void
    {
        $this->fax = $fax;
    }

    /**
     * Returns Location Api Id.
     */
    public function getLocationApiId(): ?array
    {
        return $this->locationApiId;
    }

    /**
     * Sets Location Api Id.
     *
     * @maps location_api_id
     */
    public function setLocationApiId(?array $locationApiId): void
    {
        $this->locationApiId = $locationApiId;
    }

    /**
     * Returns Location Api Key.
     */
    public function getLocationApiKey(): ?array
    {
        return $this->locationApiKey;
    }

    /**
     * Sets Location Api Key.
     *
     * @maps location_api_key
     */
    public function setLocationApiKey(?array $locationApiKey): void
    {
        $this->locationApiKey = $locationApiKey;
    }

    /**
     * Returns Location C1.
     */
    public function getLocationC1(): ?array
    {
        return $this->locationC1;
    }

    /**
     * Sets Location C1.
     *
     * @maps location_c1
     */
    public function setLocationC1(?array $locationC1): void
    {
        $this->locationC1 = $locationC1;
    }

    /**
     * Returns Location C2.
     */
    public function getLocationC2(): ?array
    {
        return $this->locationC2;
    }

    /**
     * Sets Location C2.
     *
     * @maps location_c2
     */
    public function setLocationC2(?array $locationC2): void
    {
        $this->locationC2 = $locationC2;
    }

    /**
     * Returns Location C3.
     */
    public function getLocationC3(): ?array
    {
        return $this->locationC3;
    }

    /**
     * Sets Location C3.
     *
     * @maps location_c3
     */
    public function setLocationC3(?array $locationC3): void
    {
        $this->locationC3 = $locationC3;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?array
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?array $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Office Phone.
     */
    public function getOfficePhone(): ?array
    {
        return $this->officePhone;
    }

    /**
     * Sets Office Phone.
     *
     * @maps office_phone
     */
    public function setOfficePhone(?array $officePhone): void
    {
        $this->officePhone = $officePhone;
    }

    /**
     * Returns Office Ext Phone.
     */
    public function getOfficeExtPhone(): ?array
    {
        return $this->officeExtPhone;
    }

    /**
     * Sets Office Ext Phone.
     *
     * @maps office_ext_phone
     */
    public function setOfficeExtPhone(?array $officeExtPhone): void
    {
        $this->officeExtPhone = $officeExtPhone;
    }

    /**
     * Returns Recurring Notification Days Default.
     */
    public function getRecurringNotificationDaysDefault(): ?array
    {
        return $this->recurringNotificationDaysDefault;
    }

    /**
     * Sets Recurring Notification Days Default.
     *
     * @maps recurring_notification_days_default
     */
    public function setRecurringNotificationDaysDefault(?array $recurringNotificationDaysDefault): void
    {
        $this->recurringNotificationDaysDefault = $recurringNotificationDaysDefault;
    }

    /**
     * Returns Tz.
     */
    public function getTz(): ?array
    {
        return $this->tz;
    }

    /**
     * Sets Tz.
     *
     * @maps tz
     */
    public function setTz(?array $tz): void
    {
        $this->tz = $tz;
    }

    /**
     * Returns Relationship.
     */
    public function getRelationship(): ?array
    {
        return $this->relationship;
    }

    /**
     * Sets Relationship.
     *
     * @maps relationship
     */
    public function setRelationship(?array $relationship): void
    {
        $this->relationship = $relationship;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                                  = $this->id;
        }
        if (isset($this->createdTs)) {
            $json['created_ts']                          = $this->createdTs;
        }
        if (isset($this->modifiedTs)) {
            $json['modified_ts']                         = $this->modifiedTs;
        }
        if (isset($this->accountNumber)) {
            $json['account_number']                      = $this->accountNumber;
        }
        if (isset($this->address)) {
            $json['address']                             = $this->address;
        }
        if (isset($this->brandingDomainId)) {
            $json['branding_domain_id']                  = $this->brandingDomainId;
        }
        if (isset($this->contactEmailTrxReceiptDefault)) {
            $json['contact_email_trx_receipt_default']   = $this->contactEmailTrxReceiptDefault;
        }
        if (isset($this->defaultAch)) {
            $json['default_ach']                         = $this->defaultAch;
        }
        if (isset($this->defaultCc)) {
            $json['default_cc']                          = $this->defaultCc;
        }
        if (isset($this->developerCompanyId)) {
            $json['developer_company_id']                = $this->developerCompanyId;
        }
        if (isset($this->emailReplyTo)) {
            $json['email_reply_to']                      = $this->emailReplyTo;
        }
        if (isset($this->fax)) {
            $json['fax']                                 = $this->fax;
        }
        if (isset($this->locationApiId)) {
            $json['location_api_id']                     = $this->locationApiId;
        }
        if (isset($this->locationApiKey)) {
            $json['location_api_key']                    = $this->locationApiKey;
        }
        if (isset($this->locationC1)) {
            $json['location_c1']                         = $this->locationC1;
        }
        if (isset($this->locationC2)) {
            $json['location_c2']                         = $this->locationC2;
        }
        if (isset($this->locationC3)) {
            $json['location_c3']                         = $this->locationC3;
        }
        if (isset($this->name)) {
            $json['name']                                = $this->name;
        }
        if (isset($this->officePhone)) {
            $json['office_phone']                        = $this->officePhone;
        }
        if (isset($this->officeExtPhone)) {
            $json['office_ext_phone']                    = $this->officeExtPhone;
        }
        if (isset($this->recurringNotificationDaysDefault)) {
            $json['recurring_notification_days_default'] = $this->recurringNotificationDaysDefault;
        }
        if (isset($this->tz)) {
            $json['tz']                                  = $this->tz;
        }
        if (isset($this->relationship)) {
            $json['relationship']                        = $this->relationship;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
