<?php

declare(strict_types=1);

/*
 * FortisAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace FortisAPILib\Models;

use stdClass;

class V1RecurringsDeferPaymentRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $deferCount;

    /**
     * @param int $deferCount
     */
    public function __construct(int $deferCount)
    {
        $this->deferCount = $deferCount;
    }

    /**
     * Returns Defer Count.
     * Defer Count
     */
    public function getDeferCount(): int
    {
        return $this->deferCount;
    }

    /**
     * Sets Defer Count.
     * Defer Count
     *
     * @required
     * @maps defer_count
     */
    public function setDeferCount(int $deferCount): void
    {
        $this->deferCount = $deferCount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['defer_count'] = $this->deferCount;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
